### ISSUE TITLE
Undefined symbol with torch 1.7.0 / CUDA 11

### ISSUE THREAD

**Issue by kosiokarchev** [getkeops/keops#114]
Hi, I recently updated to torch 1.7.0 and CUDA 11, and I found that this results in an import error when using keops:

```
>>> import pykeops
>>> pykeops.test_torch_bindings()
...
ImportError: /home/[USER]/.cache/pykeops-1.4.1-cpython-38/libKeOpstorch6ffe5f0b89.cpython-38-x86_64-linux-gnu.so:
undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_11DispatchKeyE
```

I'm running on Manjaro (Arch) with `python`, `python-pytorch-cuda`, `cuda`, and `gcc` (version 10) installed from the official pacman repositories. I also tried setting `CXX=g++-9`, which solved some problems I had had with previous torch/CUDA versions, but to no avail.

Finally, I also found that the same issue had been found in another project: [https://github.com/IBM/aihwkit/issues/52](https://github.com/IBM/aihwkit/issues/52).

(PS: Thanks for developing this incredibly useful library!)

**Comment by kosiokarchev** [comment]
UPDATE: Did some more testing, and it seems like everything is working correctly with a torch 1.7 without CUDA or with CUDA 10.2. In the latter case, though, I still have to modify the CMake files to use gcc8 if it is not the default version.

**Comment by bcharlier** [comment]
@kosiokarchev ,

can you check if last pypi version v1.4.2 works better ?  Thanks.

b.

**Comment by kosiokarchev** [comment]
@bcharlier, yes, no problem with the latest release, thank you!
