### ISSUE TITLE
How does keops work?

### ISSUE THREAD

**Issue by KeAWang** [getkeops/keops#14]
How does the "online map-reduce scheme" described here https://www.kernel-operations.io/keops/introduction/why_using_keops.html work to achieve linear memory? 

Also is there an option to trade off using more GPU memory to speed up computations?

**Comment by bcharlier** [comment]
Dear KeAWang,

well-mannered people say "hello" before asking a question. 

That being said, you may find how "tile reduction" used in KeOps are working in this [paper](https://www.researchgate.net/profile/Lars_Nyland/publication/291770155_Fast_N-body_simulation_with_CUDA/links/553ed7ed0cf20184050fa13c/Fast-N-body-simulation-with-CUDA.pdf?origin=publication_detail)

b.

**Comment by KeAWang** [comment]
Thanks for the reference! My apologies, I did not intend to be rude. I was just eager to understand how this amazing package worked under the hood.

**Comment by jeanfeydy** [comment]
Hi @KeAWang ,

Just to let you know that I just finished writing ~30 pages of in-depth explanations about the KeOps engine for my PhD thesis. The most useful bits should be put online relatively soon (~mid-August on the KeOps website), and the full manuscript will be available by the end of September.
Until now, we've mostly prioritized the release of introductory tutorials versus documentation of the internal engine... But this is going to change soon. 
Sorry for the delay,
Best regards,
Jean

**Comment by jeanfeydy** [comment]
P.S.: And unfortunately, to answer to your second question: no, in the general case, there is no option to "trade memory for speed". The default "GPU_1D" scheme is already nearly optimal (up to low-level profiling) and owes much of its efficiency to the elimination of intermediate storage buffers.

Note, however, that if your "matrix" or LazyTensor has very few lines and many columns, the `backend="GPU_2D"` option of Lazy tensor reductions could help you to get a sensible speed-up by mobilizing all your CUDA cores (i.e. more than one thread per line, in the case of a simple matrix-vector product or reduction with respect to the second dimension).

**Comment by jeanfeydy** [comment]
P.P.S.: Oh, by the way, I just realized that you're a colleague of Jake and Geoff! I will send the PDF to the three of you tonight :-)

**Comment by jeanfeydy** [comment]
We've just added a section "How does it work?" to the documentation, so everything should be clear now :-)

**Comment by KeAWang** [comment]
Thanks!
