### ISSUE TITLE
Logsumexp Failure

### ISSUE THREAD

**Issue by srush** [getkeops/keops#140]
I cannot seem to run the logsumexp reduction in the pytorch backend without getting a compilation error.  

The following code is executed in a fresh colab GPU environment. 

Thanks for the awesome library. 

!pip install pykeops

```python
from pykeops.torch import LazyTensor
import pykeops
pykeops.config.verbose = True
import torch
import time

N = 64
M = 2048

A = torch.ones(M, N).cuda()
B = torch.ones(M, N).cuda()
iters = 100
                                                                                                                                                                                                 begin = time.time()                              
tot = torch.zeros(Batch, M, M).float().cuda()    
A_ = LazyTensor(A[:, :, None, :])                
B_ = LazyTensor(B[:, None, :, :])                
for _ in range(iters):                           
  C = (A_ + B_).logsumexp(dim=2)                 
  tot += C                                       
  torch.cuda.synchronize()  
```

---------------------------------------------

Compiling libKeOpstorchd0a473a577 in /root/.cache/pykeops-1.4.2-cpython-36:
       formula: Max_SumShiftExp_Reduction((Var(0,64,0) + Var(1,64,1)),1)
       aliases: Var(0,64,0); Var(1,64,1); 
       dtype  : float32
... -- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - /usr/local/cuda/bin/nvcc
-- The CUDA Host CXX Compiler: /usr/bin/c++
-- The CUDA compiler identification is NVIDIA 10.1.243
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Compute properties automatically set to: -DMAXIDGPU=0;-DMAXTHREADSPERBLOCK0=1024;-DSHAREDMEMPERBLOCK0=49152
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Autodetected CUDA architecture(s):  7.5
-- Using shared_obj_name: libKeOpstorchd0a473a577
-- First i variables detected is 0
-- First j variables detected is 1
-- Compiled formula is Max_SumShiftExp_Reduction((Var(0,64,0) + Var(1,64,1)),1);  where the number of args is 2.
-- pybind11 v2.6.1 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3.6") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577

--------------------- MAKE DEBUG -----------------
Command '['cmake', '--build', '.', '--target', 'libKeOpstorchd0a473a577', '--', 'VERBOSE=1']' returned non-zero exit status 2.
/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -H/usr/local/lib/python3.6/dist-packages/pykeops -B/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577 --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/make -f CMakeFiles/Makefile2 libKeOpstorchd0a473a577
make[1]: Entering directory '/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577'
/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -H/usr/local/lib/python3.6/dist-packages/pykeops -B/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577 --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -E cmake_progress_start /root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577/CMakeFiles 5
/usr/bin/make -f CMakeFiles/Makefile2 CMakeFiles/libKeOpstorchd0a473a577.dir/all
make[2]: Entering directory '/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577'
/usr/bin/make -f CMakeFiles/keopslibKeOpstorchd0a473a577.dir/build.make CMakeFiles/keopslibKeOpstorchd0a473a577.dir/depend
make[3]: Entering directory '/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577'
cd /root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577 && /usr/local/lib/python2.7/dist-packages/cmake/data/bin/cmake -E cmake_depends "Unix Makefiles" /usr/local/lib/python3.6/dist-packages/pykeops /usr/local/lib/python3.6/dist-packages/pykeops /root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577 /root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577 /root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577/CMakeFiles/keopslibKeOpstorchd0a473a577.dir/DependInfo.cmake --color=
Dependee "/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577/CMakeFiles/keopslibKeOpstorchd0a473a577.dir/DependInfo.cmake" is newer than depender "/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577/CMakeFiles/keopslibKeOpstorchd0a473a577.dir/depend.internal".
Dependee "/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577/CMakeFiles/keopslibKeOpstorchd0a473a577.dir/depend.internal".
Scanning dependencies of target keopslibKeOpstorchd0a473a577
make[3]: Leaving directory '/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577'
/usr/bin/make -f CMakeFiles/keopslibKeOpstorchd0a473a577.dir/build.make CMakeFiles/keopslibKeOpstorchd0a473a577.dir/build
make[3]: Entering directory '/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577'
[ 20%] Building CUDA object CMakeFiles/keopslibKeOpstorchd0a473a577.dir/keops/core/link_autodiff.cu.o
/usr/local/cuda/bin/nvcc -ccbin=/usr/bin/c++ -DCUDA_BLOCK_SIZE=192 -DC_CONTIGUOUS=1 -DENABLECHUNK=1 -DKERNEL_GEOM_TYPE=0 -DKERNEL_SIG_TYPE=0 -DKERNEL_SPHERE_TYPE=0 -DMAXIDGPU=0 -DMAXTHREADSPERBLOCK0=1024 -DMODULE_NAME=libKeOpstorchd0a473a577 -DMODULE_NAME_FSHAPE_SCP=fshape_scp_gaussiangaussiangaussian_unoriented_float -DSHAREDMEMPERBLOCK0=49152 -DSUM_SCHEME=1 -DUSE_CUDA=1 -DUSE_DOUBLE=0 -DUSE_HALF=0 -D_FORCE_INLINES -D_GLIBCXX_USE_CXX11_ABI=0 -D__TYPEACC__=float -D__TYPE__=float -DkeopslibKeOpstorchd0a473a577_EXPORTS -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/local/lib/python3.6/dist-packages/pykeops -I/usr/local/lib/python3.6/dist-packages/pykeops/keops -I/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577 -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include  -gencode arch=compute_75,code=sm_75 --use_fast_math --compiler-options=-fPIC -O3 -DNDEBUG -Xcompiler=-fPIC   -include libKeOpstorchd0a473a577.h -std=c++14 -x cu -c /usr/local/lib/python3.6/dist-packages/pykeops/keops/core/link_autodiff.cu -o CMakeFiles/keopslibKeOpstorchd0a473a577.dir/keops/core/link_autodiff.cu.o
CMakeFiles/keopslibKeOpstorchd0a473a577.dir/build.make:62: recipe for target 'CMakeFiles/keopslibKeOpstorchd0a473a577.dir/keops/core/link_autodiff.cu.o' failed
make[3]: Leaving directory '/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577'
CMakeFiles/Makefile2:331: recipe for target 'CMakeFiles/keopslibKeOpstorchd0a473a577.dir/all' failed
make[2]: Leaving directory '/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577'
CMakeFiles/Makefile2:269: recipe for target 'CMakeFiles/libKeOpstorchd0a473a577.dir/rule' failed
make[1]: Leaving directory '/root/.cache/pykeops-1.4.2-cpython-36/build-libKeOpstorchd0a473a577'
Makefile:183: recipe for target 'libKeOpstorchd0a473a577' failed

--------------------- ----------- -----------------
Done.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-204ccac93d18> in <module>()
      5 A_ = LazyTensor(A[:, :, None, :])
      6 B_ = LazyTensor(B[:, None, :, :])
----> 7 f(A_, B_)
      8 begin = time.time()
      9 tot = 0

10 frames
/usr/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'libKeOpstorchd0a473a577'

**Comment by srush** [comment]
(sorry updated the code, I had the wrong code sample)

**Comment by jeanfeydy** [comment]
Hi @srush ,

Thanks for your interest in the library!

As far as I can tell, this issue is a duplicate of #125: we haven't yet added support for `.logsumexp()` reductions with vector variables, i.e. when the last dimension of your tensor is **strictly larger than 1**. 
(I have to say that I am very disappointed with our error stack trace here!)

This feature shouldn't be difficult to add on our side - but we may want to wait for our new Python-based compilation engine to be released first. What do you think @joanglaunes ?

In the short term, if your formula is indeed as easy to parallelize as in this toy example, a simple workaround would be to handle your vector dimension `N = 64` as an extra "batch" dimension:

```python
from pykeops.torch import LazyTensor
import pykeops
import torch
import time

Batch = 2
N = 64
M = 2048

A = torch.randn(Batch, M, N).cuda()
B = torch.randn(Batch, M, N).cuda()

for use_keops in [False, True]:

    if use_keops:
        a_i = LazyTensor(A.permute([0, 2, 1]).contiguous().view(Batch, N, M, 1, 1))
        b_j = LazyTensor(B.permute([0, 2, 1]).contiguous().view(Batch, N, 1, M, 1))
    else:
        a_i = A[:,:,None,:]
        b_j = B[:,None,:,:]

    iters = 100

    begin = time.time()
    tot = torch.zeros(Batch, M, N).cuda()
    for _ in range(iters):
        if use_keops:
            C = (a_i + b_j).logsumexp(dim=3).view(Batch, N, M).permute([0, 2, 1])
        else:
            C = (a_i + b_j).logsumexp(dim=2)
        tot += C
        torch.cuda.synchronize()

    print(f"Use keops? {use_keops}, time: {time.time()-begin:.3}s, value: {tot.sum():.2e}")
```
Output in Google Colab:
```
Use keops? False, time: 12.2s, value: 2.13e+08
Use keops? True, time: 0.371s, value: 2.13e+08
```

What do you think?

Best regards,
Jean

P.S.: I understand that you are an expert on NLP. Do you think that KeOps could be of any use for these applications?
As detailed in our [NeurIPS paper](https://www.jeanfeydy.com/Papers/KeOps_NeurIPS_2020.pdf) or in [this benchmark](https://www.kernel-operations.io/keops/_auto_benchmarks/h.html#sphx-glr-auto-benchmarks-plot-benchmark-high-dimension-py), symbolic "LazyTensors" are most useful when feature vectors have a small dimension (D < 10-50 is perfect) and become much less attractive on "large" variables (D > 100).

As far as we can tell, KeOps is a very good fit for e.g. geometric deep learning, but is relatively ill-suited to implement large-scale transformer networks with embeddings in spaces of dimension 1,000 or more. This last setting seems to be the most popular in the NLP literature, but we're not too sure: unfortunately, we've never had the chance to discuss with experts in this field. 
Do you have an opinion on this?

**Comment by srush** [comment]
Thanks so much, this is really interesting, and you are correct that this was the problem. 

Unfortunately, while this was the example code, my actual application is in higher dimension. I hadn't really internalized this aspect about KeOps and was always a bit confused when it was not as fast as I had been told to expect from others. 

Perhaps though we could chat about NLP sometimes? I think there are actually likely many use cases that are under explored, including some variants of transformers that might fit this use case.
