### ISSUE TITLE
Bad detection of cuda or missing dll import on windows

### ISSUE THREAD

**Issue by fradav** [getkeops/keops#151]
The [gpu_utils.py](/getkeops/keops/blob/master/pykeops/common/gpu_utils.py) isn't correct for windows (or outdated) : "cuda.dll" doesn't exist. Is this code extracted from there ?  
https://gist.github.com/f0k/63a664160d016a491b2cbea15913d549
 
For the moment I can't find the dll for driver init `cuInit()` function. I suspected it was `cudart64_110.dll` which got `cudaSetDevice()` but neither `cuInit()` nor `cuDeviceGetCount()`.

Investigating other code (numba and pytorch) to see how driver init is performed in windows.

**Comment by bcharlier** [comment]
> The gpu_utils.py isn't correct for windows (or outdated) : "cuda.dll" doesn't exist. Is this code extracted from there ?
https://gist.github.com/f0k/63a664160d016a491b2cbea15913d549

yes!
