### ISSUE TITLE
Kmeans clustering gives NaN values

### ISSUE THREAD

**Issue by RicoMontulet** [getkeops/keops#165]
When running the Kmeans clustering using Pytorch (or numpy) I get NaN values. I started looking into the function, and discovered where the NaNs come from. I created a small sample to reproduce the issue.

It assigns all points to the same cluster, which gives a div/0 since Ncl contains a 0. Not sure why it does it or how to fix it. 
I tried normilising the features since they are RGB colors (x/255.0), but that didn't help. 

When using the example from the documentation it doesn't give this issue.

If anybody has an idea, please let me know!

Code sample
```python
x = np.array([[20, 20, 20],[20, 20, 20],[20, 20, 20],[22, 22, 22],[29, 29, 29],[20, 20, 20],[20, 20, 20],[20, 20, 20],[23, 23, 23],[41, 41, 41],[20, 20, 20],[20, 20, 20],[17, 17, 17],[23, 23, 23],[50, 50, 50],[20, 20, 20],[20, 20, 20],[33, 33, 33],[27, 27, 27],[52, 52, 52],[20, 20, 20],[22, 22, 22],[45, 45, 45],[33, 33, 33],[59, 59, 59],[22, 22, 22],[47, 47, 47],[50, 50, 50],[40, 40, 40],[20, 20, 20],[22, 22, 22],[52, 52, 52],[48, 48, 48],[45, 45, 45],[20, 20, 20],[33, 33, 33],[51, 51, 51],[51, 51, 51],[51, 51, 51],[20, 20, 20],[43, 43, 43],[52, 52, 52],[52, 52, 52],[58, 58, 58],[20, 20, 20],[51, 51, 51],[53, 53, 53],[51, 51, 51],[60, 60, 60],[26, 26, 26],[45, 45, 45],[57, 57, 57],[50, 50, 50],[59, 59, 59],[44, 44, 44],[44, 44, 44],[47, 47, 47],[47, 47, 47],[20, 20, 20],[48, 48, 48],[58, 58, 58],[54, 54, 54],[51, 51, 51],[20, 20, 20],[48, 48, 48],[58, 58, 58],[66, 66, 66],[53, 53, 53],[20, 20, 20],[47, 47, 47],[55, 55, 55],[66, 66, 66],[55, 55, 55],[38, 38, 38],[46, 46, 46],[52, 52, 52],[73, 73, 73],[58, 58, 58],[50, 50, 50],[55, 55, 55],[55, 55, 55],[66, 66, 66],[61, 61, 61],[50, 50, 50],[55, 55, 55],[71, 71, 71],[54, 54, 54],[22, 22, 22],[41, 41, 41],[59, 59, 59],[68, 68, 68],[48, 48, 48],[29, 29, 29],[41, 41, 41],[61, 61, 61],[68, 68, 68],[55, 55, 55],[33, 33, 33],[45, 45, 45],[64, 64, 64],[71, 71, 71],[60, 60, 60],[55, 55, 55],[44, 44, 44],[68, 68, 68],[58, 58, 58],[59, 59, 59],[59, 59, 59],[54, 54, 54],[67, 67, 67],[62, 62, 62],[61, 61, 61],[60, 60, 60],[64, 64, 64],[68, 68, 68],[64, 64, 64],[22, 22, 22],[58, 58, 58],[58, 58, 58],[67, 67, 67],[60, 60, 60],[32, 32, 32],[62, 62, 62],[64, 64, 64],[71, 71, 71],[60, 60, 60],[46, 46, 46],[64, 64, 64],[68, 68, 68],[67, 67, 67],[61, 61, 61],[54, 54, 54],[61, 61, 61],[69, 69, 69],[74, 74, 74],[57, 57, 57],[58, 58, 58],[64, 64, 64],[69, 69, 69],[73, 73, 73],[52, 52, 52],[58, 58, 58],[65, 65, 65],[67, 67, 67],[62, 62, 62],[20, 20, 20],[57, 57, 57],[67, 67, 67],[73, 73, 73],[55, 55, 55],[26, 26, 26],[59, 59, 59],[69, 69, 69],[78, 78, 78],[46, 46, 46],[39, 39, 39],[58, 58, 58],[71, 71, 71],[80, 80, 80],[47, 47, 47],[34, 34, 34],[59, 59, 59],[73, 73, 73],[75, 75, 75],[47, 47, 47],[50, 50, 50],[61, 61, 61],[76, 76, 76],[53, 53, 53],[46, 46, 46],[57, 57, 57],[65, 65, 65],[80, 80, 80],[39, 39, 39],[19, 19, 19],[59, 59, 59],[69, 69, 69],[80, 80, 80],[40, 40, 40],[22, 22, 22],[59, 59, 59],[72, 72, 72],[80, 80, 80],[41, 41, 41],[24, 24, 24],[64, 64, 64],[74, 74, 74],[81, 81, 81],[40, 40, 40],[31, 31, 31],[68, 68, 68],[78, 78, 78],[80, 80, 80],[34, 34, 34],[40, 40, 40],[71, 71, 71],[79, 79, 79],[74, 74, 74],[24, 24, 24],[50, 50, 50],[69, 69, 69],[81, 81, 81],[75, 75, 75],[31, 31, 31],[58, 58, 58],[73, 73, 73],[79, 79, 79],[31, 31, 31],[27, 27, 27],[67, 67, 67],[73, 73, 73],[80, 80, 80],[23, 23, 23],[24, 24, 24],[73, 73, 73],[75, 75, 75],[48, 48, 48],[23, 23, 23],[27, 27, 27],[72, 72, 72],[75, 75, 75],[22, 22, 22],[23, 23, 23],[31, 31, 31],[71, 71, 71],[79, 79, 79],[24, 24, 24],[23, 23, 23],[32, 32, 32],[69, 69, 69],[29, 29, 29],[24, 24, 24],[32, 32, 32],[51, 51, 51],[67, 67, 67],[22, 22, 22],[23, 23, 23],[36, 36, 36],[68, 68, 68],[57, 57, 57],[26, 26, 26],[22, 22, 22],[32, 32, 32],[62, 62, 62],[24, 24, 24],[26, 26, 26],[22, 22, 22],[31, 31, 31],[62, 62, 62],[24, 24, 24],[26, 26, 26],[22, 22, 22],[27, 27, 27],[44, 44, 44],[24, 24, 24],[25, 25, 25],[22, 22, 22],[40, 40, 40],[19, 19, 19],[25, 25, 25],[23, 23, 23],[31, 31, 31],[67, 67, 67],[22, 22, 22],[25, 25, 25],[22, 22, 22],[29, 29, 29],[32, 32, 32],[23, 23, 23],[25, 25, 25],[22, 22, 22],[26, 26, 26],[20, 20, 20],[24, 24, 24],[24, 24, 24],[22, 22, 22]], dtype=np.float32)
x = torch.from_numpy(x)
x = x.cuda()
cl, c = KMeans(x, K=2, Niter=10, verbose=False)
print(f"X shape {x.shape}, with {len(torch.unique(x, dim=0))} unique samples\n")
print(cl, "\n")
print(c, "\n")
```
Output:
```console
X shape torch.Size([276, 3]), with 53 unique samples

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 

[[47.474636 47.474636 47.474636]
 [      nan       nan       nan]] 
```

**Comment by joanglaunes** [comment]
Hello @RicoMontulet ,
The reason is that our KMeans clustering functiuon is a bit too simplistic in the way it initializes the centroids : it just picks the K first samples. In your example with K=2, this fails because the two first samples are identical. So you have to modify slightly the KMeans function, for example you can input the centroids instead of simply the number K, and ensure you create distinct centroids, for example like this:
```
import time
import torch
from matplotlib import pyplot as plt
from pykeops.torch import LazyTensor

use_cuda = torch.cuda.is_available()
dtype = torch.float32 if use_cuda else torch.float64

def KMeans(x, c, Niter=10, verbose=True):

    K = len(c)

    start = time.time()
    N, D = x.shape  # Number of samples, dimension of the ambient space

    x_i = LazyTensor(x.view(N, 1, D))  # (N, 1, D) samples
    c_j = LazyTensor(c.view(1, K, D))  # (1, K, D) centroids

    # K-means loop:
    # - x  is the (N, D) point cloud,
    # - cl is the (N,) vector of class labels
    # - c  is the (K, D) cloud of cluster centroids
    for i in range(Niter):

        # E step: assign points to the closest cluster -------------------------
        D_ij = ((x_i - c_j) ** 2).sum(-1)  # (N, K) symbolic squared distances
        cl = D_ij.argmin(dim=1).long().view(-1)  # Points -> Nearest cluster

        # M step: update the centroids to the normalized cluster average: ------
        # Compute the sum of points per cluster:
        c.zero_()
        c.scatter_add_(0, cl[:, None].repeat(1, D), x)

        # Divide by the number of points per cluster:
        Ncl = torch.bincount(cl, minlength=K).type_as(c).view(K, 1)
        c /= Ncl  # in-place division to compute the average

    if verbose:  # Fancy display -----------------------------------------------
        if use_cuda:
            torch.cuda.synchronize()
        end = time.time()
        print(
            f"K-means for the Euclidean metric with {N:,} points in dimension {D:,}, K = {K:,}:"
        )
        print(
            "Timing for {} iterations: {:.5f}s = {} x {:.5f}s\n".format(
                Niter, end - start, Niter, (end - start) / Niter
            )
        )

    return cl, c

import numpy as np
x = np.array([[20, 20, 20],[20, 20, 20],[20, 20, 20],[22, 22, 22],[29, 29, 29],[20, 20, 20],[20, 20, 20],[20, 20, 20],[23, 23, 23],[41, 41, 41],[20, 20, 20],[20, 20, 20],[17, 17, 17],[23, 23, 23],[50, 50, 50],[20, 20, 20],[20, 20, 20],[33, 33, 33],[27, 27, 27],[52, 52, 52],[20, 20, 20],[22, 22, 22],[45, 45, 45],[33, 33, 33],[59, 59, 59],[22, 22, 22],[47, 47, 47],[50, 50, 50],[40, 40, 40],[20, 20, 20],[22, 22, 22],[52, 52, 52],[48, 48, 48],[45, 45, 45],[20, 20, 20],[33, 33, 33]…31, 31],[62, 62, 62],[24, 24, 24],[26, 26, 26],[22, 22, 22],[27, 27, 27],[44, 44, 44],[24, 24, 24],[25, 25, 25],[22, 22, 22],[40, 40, 40],[19, 19, 19],[25, 25, 25],[23, 23, 23],[31, 31, 31],[67, 67, 67],[22, 22, 22],[25, 25, 25],[22, 22, 22],[29, 29, 29],[32, 32, 32],[23, 23, 23],[25, 25, 25],[22, 22, 22],[26, 26, 26],[20, 20, 20],[24, 24, 24],[24, 24, 24],[22, 22, 22]], dtype=np.float32)
x = torch.from_numpy(x)
x = x.cuda()

# create unique initial centroids
K = 2
c = torch.unique(x, dim=0)[:K]

cl, c = KMeans(x, c, Niter=10, verbose=False)
print(f"There are {len(x)} samples with {len(torch.unique(x, dim=0))} unique samples", "\n")
print(cl, "\n")
print(c, "\n")
```

**Comment by RicoMontulet** [comment]
> Hello @RicoMontulet ,
> The reason is that our KMeans clustering functiuon is a bit too simplistic in the way it initializes the centroids : it just picks the K first samples. In your example with K=2, this fails because the two first samples are identical. So you have to modify slightly the KMeans function, for example you can input the centroids instead of simply the number K, and ensure you create distinct centroids, for example like this:
> 
> ```
> import time
> import torch
> from matplotlib import pyplot as plt
> from pykeops.torch import LazyTensor
> 
> use_cuda = torch.cuda.is_available()
> dtype = torch.float32 if use_cuda else torch.float64
> 
> def KMeans(x, c, Niter=10, verbose=True):
> 
>     K = len(c)
> 
>     start = time.time()
>     N, D = x.shape  # Number of samples, dimension of the ambient space
> 
>     x_i = LazyTensor(x.view(N, 1, D))  # (N, 1, D) samples
>     c_j = LazyTensor(c.view(1, K, D))  # (1, K, D) centroids
> 
>     # K-means loop:
>     # - x  is the (N, D) point cloud,
>     # - cl is the (N,) vector of class labels
>     # - c  is the (K, D) cloud of cluster centroids
>     for i in range(Niter):
> 
>         # E step: assign points to the closest cluster -------------------------
>         D_ij = ((x_i - c_j) ** 2).sum(-1)  # (N, K) symbolic squared distances
>         cl = D_ij.argmin(dim=1).long().view(-1)  # Points -> Nearest cluster
> 
>         # M step: update the centroids to the normalized cluster average: ------
>         # Compute the sum of points per cluster:
>         c.zero_()
>         c.scatter_add_(0, cl[:, None].repeat(1, D), x)
> 
>         # Divide by the number of points per cluster:
>         Ncl = torch.bincount(cl, minlength=K).type_as(c).view(K, 1)
>         c /= Ncl  # in-place division to compute the average
> 
>     if verbose:  # Fancy display -----------------------------------------------
>         if use_cuda:
>             torch.cuda.synchronize()
>         end = time.time()
>         print(
>             f"K-means for the Euclidean metric with {N:,} points in dimension {D:,}, K = {K:,}:"
>         )
>         print(
>             "Timing for {} iterations: {:.5f}s = {} x {:.5f}s\n".format(
>                 Niter, end - start, Niter, (end - start) / Niter
>             )
>         )
> 
>     return cl, c
> 
> import numpy as np
> x = np.array([[20, 20, 20],[20, 20, 20],[20, 20, 20],[22, 22, 22],[29, 29, 29],[20, 20, 20],[20, 20, 20],[20, 20, 20],[23, 23, 23],[41, 41, 41],[20, 20, 20],[20, 20, 20],[17, 17, 17],[23, 23, 23],[50, 50, 50],[20, 20, 20],[20, 20, 20],[33, 33, 33],[27, 27, 27],[52, 52, 52],[20, 20, 20],[22, 22, 22],[45, 45, 45],[33, 33, 33],[59, 59, 59],[22, 22, 22],[47, 47, 47],[50, 50, 50],[40, 40, 40],[20, 20, 20],[22, 22, 22],[52, 52, 52],[48, 48, 48],[45, 45, 45],[20, 20, 20],[33, 33, 33]…31, 31],[62, 62, 62],[24, 24, 24],[26, 26, 26],[22, 22, 22],[27, 27, 27],[44, 44, 44],[24, 24, 24],[25, 25, 25],[22, 22, 22],[40, 40, 40],[19, 19, 19],[25, 25, 25],[23, 23, 23],[31, 31, 31],[67, 67, 67],[22, 22, 22],[25, 25, 25],[22, 22, 22],[29, 29, 29],[32, 32, 32],[23, 23, 23],[25, 25, 25],[22, 22, 22],[26, 26, 26],[20, 20, 20],[24, 24, 24],[24, 24, 24],[22, 22, 22]], dtype=np.float32)
> x = torch.from_numpy(x)
> x = x.cuda()
> 
> # create unique initial centroids
> K = 2
> c = torch.unique(x, dim=0)[:K]
> 
> cl, c = KMeans(x, c, Niter=10, verbose=False)
> print(f"There are {len(x)} samples with {len(torch.unique(x, dim=0))} unique samples", "\n")
> print(cl, "\n")
> print(c, "\n")
> ```

Thank you! I changed the Kmeans to get K unique clusters itself and now it works! :)
