### ISSUE TITLE
A small BUG in type analysis

### ISSUE THREAD

**Issue by wzm2256** [getkeops/keops#167]
The else block in line 118 in https://github.com/getkeops/keops/blob/master/pykeops/common/get_options.py is not indented correctly. There should be one more indent.

The current version will report an error "local variable 'MemType' referenced before assignment" when the input type is not expected, because the else block therein is not run when the if condition in line 99 is not satisfied.

It is just a small bug and I think it is not necessary to make a pull request.

**Comment by joanglaunes** [comment]
Hello @wzm2256 ,
Ok thank you for this report. In fact I think we need to repeat the else statement twice, one for the inner if and one for the outer.

**Comment by wzm2256** [comment]
Sure, it's up to you guys to decide.
Thanks for providing this wonderful tool.

Please feel free to close this issue.
