### ISSUE TITLE
How can I use cpu only for the keops?

### ISSUE THREAD

**Issue by YifanDengWHU** [getkeops/keops#176]
I have spent a lot of time dealing with the CUDA support problem. However, I don't have much experience and enough permission to deal with nvcc, cmake. So I decided to use CPU only to run through the data pipeline of a specific project. It said that I only need to set tagHostDevice=0, so where can I change this arrtibute? 
Thanks!

**Comment by hypnopump** [comment]
This is also discussed here: https://github.com/getkeops/keops/issues/170

The simplest answer would be: In the same session in which you will run the scripts, run `export CUDA_VISIBLE_DEVICES=` before, the run the pykeops script. 

Hope this helps!
Eric Alcaide

**Comment by YifanDengWHU** [comment]
Thanks!
