### ISSUE TITLE
PyKeops test not passing on CI

### ISSUE THREAD

**Issue by gdurif** [getkeops/keops#184]
Issue with test on MacOS

c.f. https://ci.inria.fr/keops/blue/organizations/jenkins/keops/detail/PR-183/1/pipeline

**Comment by gdurif** [comment]
I am still merging #183 as I only modified RKeOps related files and local tests and checks pass.

**Comment by joanglaunes** [comment]
Hello @gdurif ,
It looks like the CI on MacOS works now, can we say this is fixed and close the issue ?

**Comment by gdurif** [comment]
Hi, yes, no problem, I'm doing it now.
