### ISSUE TITLE
Where is the file for module benchmark_utils?

### ISSUE THREAD

**Issue by liuzhy71** [getkeops/keops#287]
I was trying to run the benchmark on KNN, however, I cannot find the module benchmark_utils?
Where can I find the file containing this module?

**Comment by jeanfeydy** [comment]
Hi @liuzhy71 ,

Thanks for your interest in the library!
Everything you need to run the KNN benchmarks is available in this folder: https://github.com/getkeops/keops/tree/main/pykeops/pykeops/benchmarks
If you run into an issue reproducing some of our experiments, please let us know.

Best regards,
Jean
