### ISSUE TITLE
cant import test_torch_bindings

### ISSUE THREAD

**Issue by hududed** [getkeops/keops#295]
I am trying to run a notebook on a hpc cluster from a conda environment with a fresh install of `pytorch` and `pykeops` library. Torch found my GPU find but get the error when importing:

```
import torch
torch.cuda.get_device_name()
'Tesla P100-PCIE-16GB'

from pykeops import test_torch_bindings
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[22], line 1
----> 1 from pykeops import test_torch_bindings

ImportError: cannot import name 'test_torch_bindings' from 'pykeops' (/home/hwahab/.conda/envs/synth/lib/python3.10/site-packages/pykeops/__init__.py)
```

I am guessing somehow it's not detecting the cuda device. How to troubleshoot?

**Comment by bcharlier** [comment]
Hi @hududed ,

Your import are wrong: should be

import pykeops
pykeops.test_torch_bindings()

Hope it will work.
