### ISSUE TITLE
Pykeops cannot find cuda 

### ISSUE THREAD

**Issue by hichamjanati** [getkeops/keops#3]
Hello, great work !

With this sample code, pykeops cannot see the GPUs with cuda 9.1 and cmake 3.12.1, is that normal ?
```
(base) hjanati@drago3:~/code/nips19$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```
I made sure I installed pykeops with all dependencies pykeops[full].

```python
import numpy as np
import pykeops
pykeops.verbose = True
from pykeops.numpy import Genred

x = np.arange(1, 10).reshape(-1, 3).astype('float32')
y = np.arange(3, 9 ).reshape(-1, 3).astype('float32')

my_conv = Genred('-SqNorm2(x-y)', ['x = Vi(3)', 'y = Vj(3)'])
print(my_conv(x, y))
```

Here is the output:

```
Compiling libKeOpsnumpy73a835aa5f in /home/parietal/hjanati/.cache/pykeops-1.0.2/:
       formula: Sum_Reduction(-SqNorm2(x-y),1)
       aliases: x = Vi(0,3); y = Vj(1,3); 
       dtype  : float64
... CMake Warning at /home/parietal/hjanati/miniconda3/share/cmake-3.14/Modules/FindCUDA.cmake:893 (message):
  Expecting to find librt for libcudart_static, but didn't find it.
Call Stack (most recent call first):
  keops/cuda.cmake:8 (find_package)
  CMakeLists.txt:11 (include)


-- No GPU detected. USE_CUDA set to FALSE.
-- Using shared_obj_name: libKeOpsnumpy73a835aa5f
-- pybind11 v2.2.4
-- Configuring done
-- Generating done
-- Build files have been written to: /home/parietal/hjanati/.cache/pykeops-1.0.2

Scanning dependencies of target keopslibKeOpsnumpy73a835aa5f
[ 25%] Building CXX object CMakeFiles/keopslibKeOpsnumpy73a835aa5f.dir/keops/core/link_autodiff.cpp.o
[ 50%] Linking CXX shared library libKeOpsnumpy73a835aa5f.so
[ 50%] Built target keopslibKeOpsnumpy73a835aa5f
Scanning dependencies of target libKeOpsnumpy73a835aa5f
[ 75%] Building CXX object CMakeFiles/libKeOpsnumpy73a835aa5f.dir/numpy/generic/generic_red.cpp.o
[100%] Linking CXX shared module libKeOpsnumpy73a835aa5f.cpython-36m-x86_64-linux-gnu.so
[100%] Built target libKeOpsnumpy73a835aa5f

Done. 
Traceback (most recent call last):
  File "keopstest.py", line 10, in <module>
    print(my_conv(x, y))
  File "/home/parietal/hjanati/miniconda3/lib/python3.6/site-packages/pykeops/numpy/generic/generic_red.py", line 224, in __call__
    out = self.myconv.genred_numpy(nx, ny, tagCpuGpu, tag1D2D, 0, device_id, ranges, *args)
RuntimeError: [KeOps]\xa0This KeOps shared object has been compiled without cuda support: 
 1) to perform computations on CPU, simply set tagHostDevice to 0
 2) to perform computations on GPU, please recompile the formula with a working version of cuda.
```

**Comment by jeanfeydy** [comment]
Hi Hicham,

Once again, thanks for the detailed report!
This time, it looks like a problem with CMake and your library path: the standard [`FindCUDA`](https://cmake.org/cmake/help/latest/module/FindCUDA.html) script could not find the `libcudart_static` library, as referenced e.g. by [this thread on the NVidia devtalk forum](https://devtalk.nvidia.com/default/topic/1030854/jetson-tx2/error-happend-during-cross-compile-in-ubuntu-for-jetson-ext2-expecting-to-find-librt-for-libcudart_s-/). Could you please report the result of the

```bash
locate libcudart_static
```
command? If `locate` is not installed on your machine,

```bash
sudo apt-get install mlocate
sudo updatedb
```

should do the trick. For reference, the output on my laptop:

```bash
jean@jean-XPS-15-9550:~$ locate libcudart_static
/usr/lib/x86_64-linux-gnu/libcudart_static.a
```

And on a new Google Colab session:
```bash
!sudo apt-get install mlocate
!sudo updatedb
!locate libcudart_static

/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart_static.a
```
If `locate` cannot find the `libcudart_static` file in your CUDA install, [updating the `ldpath` with `ldconfig`](https://stackoverflow.com/questions/10808958/why-cant-libcudart-so-4-be-found-when-compiling-the-cuda-samples-under-ubuntu) may allow you to fix this problem.

N.B. for @bcharlier : [`FindCUDA`](https://cmake.org/cmake/help/latest/module/FindCUDA.html) has recently been deprecated by Kitware/CMake. Long-term, we may have to switch to their new "first-class" support for CUDA.

**Comment by bcharlier** [comment]
Hi Hicham,

In your issue  #https://github.com/getkeops/keops/issues/2#issue-445628892 cmake seems to have found the nvidia stuff as the line tells us : 
`
-- Autodetected CUDA architecture(s):  6.0 6.0 6.0 3.7 3.7 3.7 3.7 3.7 3.7 3.7 3.7 3.7 3.7
`
This should corresponds to the compute capability of the 13 GPUs (?!) available on your system. Is that correct ? if not please provide the output of `nvidia-smi`.

In any cases, the `FindCuda` module of cmake don't do much than looking in `/usr/local/cuda`... So, the best practice is to contact the admin to create a symbolic /usr/local/cuda link to the last cuda lib installed on your system. As documented here, https://cmake.org/cmake/help/latest/module/FindCUDA.html :  

> To use a different installed version of the toolkit set the environment variable CUDA_BIN_PATH before running cmake (e.g. CUDA_BIN_PATH=/usr/local/cuda1.0 instead of the default /usr/local/cuda)

That is not very handy when using keops from python... even if it could be done in your conda env.

Hope this helps.

b.


PS :  @jeanfeydy, in fact, we use a mixture of "first-class" support of cuda language and the old FindCuda module. As a matter of fact, the "first class" support of CUDA by cmake was still young as of 2018/19. The good old FindCuda module has some features (mainly for detection purposes like the internal cmake variables CUDA_NVCC_EXECUTABLE, CUDA_FOUND, etc...) that are not available when simply use a `enable_language(CUDA)`. As cmake is moving quickliy this could change in a near future...

**Comment by gdebie** [comment]
Hi,
I am using the same server as Hicham hence encountering the same issues. Could you elaborate on how to set CUDA_BIN_PATH locally in a conda env?
Many thanks!

Gwendoline

**Comment by bcharlier** [comment]
For conda, you should find an how-to in the doc here: 
https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#macos-and-linux

But, I repeat my question: are all your GPU well recognize? that is, is this line in issure #2

> -- Autodetected CUDA architecture(s): 6.0 6.0 6.0 3.7 3.7 3.7 3.7 3.7 3.7 3.7 3.7 3.7 3.7

correct ?
b.

**Comment by jeanfeydy** [comment]
Hi Benjamin,
Just a quick note on these two issues: according to a mail that Hicham sent me last week, #2 is on "Marco's machine" hosted by the MokaPlan Inria team at Gare de Lyon, while this issue #3 is on the machine of the Parietal Inria team at Neurospin. 
As far as I can tell, the problems are not 100% the same for both configurations, so it may be best to keep both tracks separate, waiting for Hicham to come back to these issues ;-)

**Comment by bcharlier** [comment]
This is most likely due to a system configuration problem. I close the issue for now. Do not hesitate to re-open it if needed.

**Comment by atechnicolorskye** [comment]
Hi @bcharlier ,

I'm having similar issues where cuda exists and torch finds it but pykeops doesn't.

I ran: import pykeops
         pykeops.verbose = True
         pykeops.build_type = 'Debug'
         pykeops.clean_pykeops()
         pykeops.test_torch_bindings()

And get:

  Environment variable CUDA_ROOT is set to:

    /usr/local/cuda

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  CMakeLists.txt:15 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The CXX compiler identification is GNU 9.2.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- No GPU detected. USE_CUDA set to FALSE.

.....

RuntimeError: [KeOps] This KeOps shared object has been compiled without cuda support:
 1) to perform computations on CPU, simply set tagHostDevice to 0
 2) to perform computations on GPU, please recompile the formula with a working version of cuda.

Cheers

**Comment by daidedou** [comment]
> In any cases, the `FindCuda` module of cmake don't do much than looking in `/usr/local/cuda`... So, the best practice is to contact the admin to create a symbolic /usr/local/cuda link to the last cuda lib installed on your system. As documented here, https://cmake.org/cmake/help/latest/module/FindCUDA.html :
> 
> > To use a different installed version of the toolkit set the environment variable CUDA_BIN_PATH before running cmake (e.g. CUDA_BIN_PATH=/usr/local/cuda1.0 instead of the default /usr/local/cuda)

Hi, I tried to dig a little more inside the problem. It appears from reading your code that you were thinking of this line  https://github.com/getkeops/keops/blob/ae0b921cad1367255d71f96359a68256c18707c5/keops/cuda.cmake#L12 right?

But apparently it appears after, I made an "empty" cmakelists, with other stuff to find CUDA, and it works fine: 
`
cmake_minimum_required(VERSION 3.7)
project(myproject)

#enable_language("CUDA")
find_package(CUDA QUIET)


# Check for CUDA ENV vars
IF(NOT DEFINED ENV{CUDA_PATH})
    MESSAGE(FATAL_ERROR "CUDA_PATH Environment variable is not set.")
ENDIF(NOT DEFINED ENV{CUDA_PATH})

# Set the toolkit path
FILE(TO_CMAKE_PATH "$ENV{CUDA_PATH}" CUDA_TOOLKIT_ROOT_DIR)
SET(CUDA_TOOLKIT_ROOT_DIR ${CUDA_TOOLKIT_ROOT_DIR} CACHE STRING "Root directory of the Cuda Library" FORCE)

# Find the package
find_package(CUDA REQUIRED)

# Create and interface library as a link target (Requires CMake 3.7.0+)
add_library(cuda INTERFACE)
set_target_properties(cuda PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES ${CUDA_INCLUDE_DIRS}
    INTERFACE_LINK_LIBRARIES "${CUDA_LIBRARIES};${CUDA_CUFFT_LIBRARIES};${CUDA_CUBLAS_LIBRARIES}"
)

SET(CUDA_HOST_COMPILATION_CPP ON)
`
And no problem from there, so it seems to be your manual scripts that doesn't find CUDA in our configuration. If you have any infos about how you made it (I don't know anything about Cmake), just tell me. I will try to continue digging into the problem. 

Thanks for the library by the way :)

**Comment by daidedou** [comment]
Hi,

I tried to dig on the problem on my own but I don't know anything about cmake. 
When you say :
> In any cases, the `FindCuda` module of cmake don't do much than looking in `/usr/local/cuda`... So, the best practice is to contact the admin to create a symbolic /usr/local/cuda link to the last cuda lib installed on your system. As documented here, https://cmake.org/cmake/help/latest/module/FindCUDA.html :
> 
> > To use a different installed version of the toolkit set the environment variable CUDA_BIN_PATH before running cmake (e.g. CUDA_BIN_PATH=/usr/local/cuda1.0 instead of the default /usr/local/cuda)

You were thinking about this line:
https://github.com/getkeops/keops/blob/ae0b921cad1367255d71f96359a68256c18707c5/keops/CMakeLists.txt#L12

Right?

But I tested an "empty" cmake that tries to find cuda: 
<script src="https://gist.github.com/daidedou/dc0e43070195d3b4f8899eed3fc3062f.js"></script>
It appears that cmake says that cuda is found:
-- Found CUDA: /usr/local/cuda (found version "10.2") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/machin/Documents/these/build

So the problem might as well come from your handmade script that counts the GPUs, but not from finding CUDA. If you want to share any information about what you wanted to do (it seems simple but meh), I could try continue digging on my own. 

It might be also interesting to reopen the issue.

**Comment by daidedou** [comment]
Ok so you were right it was a configuration problem. I'm on Fedora and there is a lot of things to do in order to get CUDA working. There is a specific version of g++ to install and I need to pass -ccbin=cuda-g++ each time.

My problem was that this part :
https://github.com/getkeops/keops/blob/ae0b921cad1367255d71f96359a68256c18707c5/keops/CMakeLists.txt#L18-L45

use in the end nvcc without the flag. I also had to set the value CMAKE_CUDA_HOST_COMPILER cuda-g++.

But still it is too much linked to my configuration.
I guess that if you want to check whether you are able to find cuda or not, you should do the following (describing a lot for the unfamiliar with cmake like me):

- create an empty folder, and put a file named CMakeLists.txt inside it, filled with this code: 
https://gist.github.com/daidedou/dc0e43070195d3b4f8899eed3fc3062f

- create a folder named "build", when inside it, launch 'cmake ..' in the command line

- if it fails to find cuda, it means that findcuda is failing

- if not, change CMakeLists.txt by this one : https://gist.github.com/daidedou/700cd87d6e24fbff1e2190fad1224c08

- relaunch cmake .. inside build, it will fail and create a file named detect_cuda_props.cu

- Then run nvcc --run detect_cuda_props.cu, you will have a proper error on which you can dig (if pytorch does in fact detect your GPUs!)

Hope it will help someone!
