### ISSUE TITLE
munmap_chunk(): invalid pointer  *** Break *** abort

### ISSUE THREAD

**Issue by YAndrewL** [getkeops/keops#334]
This error happens every time I run keops, please kindly inform the reason?

**Comment by joanglaunes** [comment]
Hello @YAndrewL ,
Sorry for the late reply. Can you provide with more information about your configuration and the script you are running, and also could you test the latest version of KeOps on the main git branch to see if the error is still present?

**Comment by YAndrewL** [comment]
Sorry for not continuing this issue, the error has gone when I update all indenpendicies to the newest version like pykeops and pytorch, I can mark this as solved.
