### ISSUE TITLE
How to install the latest version in github?

### ISSUE THREAD

**Issue by YAndrewL** [getkeops/keops#347]
Hi, I found that the main branch in Github now supprots the comparision operations, how to install the latest branches using like Pip? Thanks a lot!

**Comment by joanglaunes** [comment]
Hello @YAndrewL ,
You can install it with these commands :
``` bash
pip install git+https://github.com/getkeops/keops.git@main#subdirectory=keopscore
pip install git+https://github.com/getkeops/keops.git@main#subdirectory=pykeops
```

**Comment by YAndrewL** [comment]
Hi @joanglaunes ,thank you so much for the reply!
