### ISSUE TITLE
Issue importing `pykeops_nvrtc`

### ISSUE THREAD

**Issue by Louis-Pujol** [getkeops/keops#352]
Hi,

I had some trouble with the line 
https://github.com/getkeops/keops/blob/dcec73cb066ecf4c13efe7612a585022123d6224/pykeops/pykeops/common/keops_io/LoadKeOps_nvrtc.py#L20

The `build_folder` is added to `sys.path` when pykeops is imported. But if the `build_folder` is manually removed from `sys.path` later, the `pykeops_nvrtc` will not be find. As an example

```python
import sys
from copy import deepcopy
syspath = deepcopy(sys.path)

import pykeops

# Reset sys.path to its value before importing pykeops
sys.path = syspath

pykeops.test_torch_bindings()
``` 

leads to a import error. Seems that this modification
```python
pykeops_nvrtc = importlib.import_module( get_build_folder() + "/pykeops_nvrtc")
```
can make this part of the code robust to malicious `sys.path` modifications.

**Comment by jeanfeydy** [comment]
Hi @bcharlier , @joanglaunes , do you see any reason not to apply this one-line fix?
If I remember correctly, this problem comes up with Mkdocs-gallery (or is it sphinx?), that resets the path between every "cell" of the pseudo-notebook.

**Comment by Louis-Pujol** [comment]
Yes that was the issue, mkdocs-gallery reset `sys.path` between cells. It leaded to `ModuleNotFoundError` if `pykeops` was just imported in a cell and a function that requires `pykeops_nvrtc` was called in another cell.

I've just realized that the solution proposed in the initial message doesn't work (`import_module` expects python packages, not paths). This is better:
```python
if pykeops.get_build_folder() not in sys.path:
    sys.path.append(pykeops.get_build_folder())
importlib.import_module("pykeops_nvrtc")
```

With a test:
```python
import pytest
import importlib
import sys
from copy import deepcopy

syspath = deepcopy(sys.path) # Save the original sys.path
import pykeops
sys.path = syspath # Reset sys.path to its value before importing pykeops

# pykeops_nvrtc is not importable
with pytest.raises(ModuleNotFoundError):
    importlib.import_module("pykeops_nvrtc") # This raises an error

# With the above fix, pykeops_nvrtc is importable
if pykeops.get_build_folder() not in sys.path:
    sys.path.append(pykeops.get_build_folder())
module = importlib.import_module("pykeops_nvrtc")
```

**Comment by bcharlier** [comment]
@Louis-Pujol , interresting. 

Not sure it is related, but : I have also notice that under a new python venv. If keops is imported undirectly (`from pykeops.torch import Vi` say) keopscore (in fact ld) fails to detect libnvrt...

```
[KeOps] Compiling cuda jit compiler engine ... 
[KeOps] Warning : There were warnings or errors :
/usr/bin/ld: cannot find -lnvrtc: No such file or directory
collect2: error: ld returned 1 exit status
```
Importing directly works:

```
$ python -m pykeops
 
[KeOps] Compiling cuda jit compiler engine ... OK
[pyKeOps] Compiling nvrtc binder for python ... OK

```

**Comment by joanglaunes** [comment]
Hello all,
I do not see any problem with this modification, I guess it should be ok!
