### ISSUE TITLE
Memory leak in Pykeops 2.2 not present in 2.1.2

### ISSUE THREAD

**Issue by danjjackson** [getkeops/keops#353]
I have a convolutional layer implementing a convolution over a point cloud using Pykeops. Using v2.1.2 this all works fine, in v2.2 this causes a memory leak that eventually crashes the training

```
from torch import nn
from pykeops.torch import LazyTensor

class ConvLayer(nn.Module):
    def __init__(
        self,
        in_channels: int,
        hidden_units: int,
        out_channels: int,
        radius: float,
    ):
        """
        Creates the KeOps convolution layer.

        Args:
            in_channels: dimension of input features
            hidden_units (int, optional): number of hidden uniots per point.
                Defaults to out_channels.
            out_channels: dimension of output features per point.
            radius : deviation of the Gaussian window on the
                quasi-geodesic distance `d_ij`. Defaults to 1..

        """

        super().__init__()

        self.radius = radius
        
        # 3D convolution filters, encoded as an MLP:
        self.conv = nn.Sequential(
            nn.Linear(3, hidden_units),
            nn.ReLU(), 
            nn.Linear(hidden_units, out_channels),
        )

def forward(
        self, points: Tensor, nuv: Tensor, features: Tensor, ranges=None, batch=None
    ):
        """
        points, local basis, in features  ->  out features
        (N, 3),   (N, 3, 3),    (N, I)    ->    (N, O)

        Args:
            points (Tensor): (N,3) point coordinates `x_i`.
            nuv (Tensor): (N,3,3) local coordinate systems `[n_i,u_i,v_i]`.
            features (Tensor): (N,I) input feature vectors `f_i`.

        Returns:
            (Tensor): (N,O) output feature vectors `f'_i`.
        """

        # Normalize the kernel radius:
        points = points / (sqrt(2.0) * self.radius)  # (N, 3)

        # Vertices:
        x_i = LazyTensor(points[:, None, :].contiguous())  # (N, 1, 3)
        x_j = LazyTensor(points[None, :, :].contiguous())  # (1, N, 3)

        normals = nuv[:, 0, :].contiguous().detach()

        # Local bases:
        nuv_i = LazyTensor(nuv.view(-1, 1, 9))  # (N, 1, 9)
        
        # Normals:
        n_i = nuv_i[:3]  # (N, 1, 3)
        n_j = LazyTensor(normals[None, :, :].contiguous())  # (1, N, 3)

        # Pseudo-geodesic squared distance:
        d2_ij = ((x_j - x_i) ** 2).sum(-1) * ((2 - (n_i | n_j)) ** 2)  # (N, N, 1)
        # Gaussian window:
        window_ij = (-d2_ij).exp()  # (N, N, 1)

        # Local coordinates:
        X_ij = nuv_i.matvecmult(x_j - x_i) 

        A_1, B_1 = self.conv[0].weight, self.conv[0].bias
        A_2, B_2 = self.conv[2].weight, self.conv[2].bias
        a_1 = LazyTensor(A_1.view(1, 1, -1))  # (1, 1, C*3)
        b_1 = LazyTensor(B_1.view(1, 1, -1))  # (1, 1, C)
        a_2 = LazyTensor(A_2.view(1, 1, -1))  # (1, 1, Hd*C)
        b_2 = LazyTensor(B_2.view(1, 1, -1))  # (1, 1, Hd)
        # MLP:
        X_1 = a_1.matvecmult(X_ij) + b_1  # (N, N, C)
        X_2 = X_1.relu()  # (N, N, C)
        X_3 = a_2.matvecmult(X_2) + b_2  # (N, N, Hd)
        X_4 = X_3.relu()

        f_j = LazyTensor(features[None, :, :].contiguous())
        F_ij = window_ij * X_4 * f_j
        conv_features = F_ij.sum(dim=1)
        return conv_features
```
Version 2.2:
<img width="500" alt="Version 2.2" src="https://github.com/getkeops/keops/assets/52429462/7d36a7e8-2a98-4f9e-a4fe-74b47d25303d">

Version 2.1.2:
<img width="500" alt="Version 2.1.2" src="https://github.com/getkeops/keops/assets/52429462/d1614e02-5298-4e53-a4c8-37a8dccfc5d8">

**Comment by bcharlier** [comment]
Hi @danjjackson ,

first graph is KeOps v2.1.2  and second one is v2.2 ?

**Comment by danjjackson** [comment]
Hi, yes, that's correct

**Comment by bcharlier** [comment]
Some test:
- I experience an increasing mem consumption on my GPU along the loop.
- Removing the cache does not help
- leaks size does depend on size n and m below

```python
import torch.cuda
from pykeops.torch import Vi, Vj, LazyTensor

def keops_knn(x, y):
    xi = LazyTensor(x[:, None, :])
    xj = LazyTensor(y[None, :, :])
    dij = ((xi - xj) ** 2).sum(-1)
    knn_func = dij.sum_reduction(dim=0)
    return knn_func

d = 1
n, m = 1, 1
q_points = torch.rand((n, d)).requires_grad_(True).to("cuda")
s_points = torch.rand((m, d)).to("cuda")

s = [0]
for i in range(100):
    result = keops_knn(q_points, s_points)
    s.append(torch.cuda.memory.memory_stats()["allocated_bytes.all.current"])
    print("Current mem: ", s[-1], "diff: ", s[-1] - s[-2])
```

```
Current mem:  1536 diff:  1536
Current mem:  2048 diff:  512
Current mem:  2560 diff:  512
Current mem:  2048 diff:  -512
Current mem:  2560 diff:  512
Current mem:  3072 diff:  512
Current mem:  3584 diff:  512
Current mem:  4096 diff:  512
Current mem:  4608 diff:  512
Current mem:  2560 diff:  -2048
Current mem:  3072 diff:  512
Current mem:  3584 diff:  512
Current mem:  4096 diff:  512
Current mem:  4608 diff:  512
Current mem:  5120 diff:  512
Current mem:  5632 diff:  512
Current mem:  6144 diff:  512
Current mem:  6656 diff:  512
Current mem:  7168 diff:  512
Current mem:  7680 diff:  512
Current mem:  3584 diff:  -4096
Current mem:  4096 diff:  512
Current mem:  4608 diff:  512
Current mem:  5120 diff:  512
Current mem:  5632 diff:  512
Current mem:  6144 diff:  512
Current mem:  6656 diff:  512
Current mem:  7168 diff:  512
Current mem:  7680 diff:  512
Current mem:  8192 diff:  512
Current mem:  8704 diff:  512
Current mem:  9216 diff:  512
Current mem:  9728 diff:  512
Current mem:  10240 diff:  512
Current mem:  4096 diff:  -6144
...
```

**Comment by Damowerko** [comment]
@bcharlier Do you observe a similar connection to the version v2.1.2 vs v2.2?

**Comment by bcharlier** [comment]
No leaks with v2.1.2. Logs are clean

```
Allocated mem:  1536 diff:  1536
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
Allocated mem:  1536 diff:  0
```

**Comment by Damowerko** [comment]
@bcharlier Is your cuda or PyTorch version different between the two tests?

**Comment by bcharlier** [comment]
After git-bisect I found this commit b1b304d8 to be the turning point where leak appears.

**Comment by bcharlier** [comment]
Seems related to https://pytorch.org/docs/stable/generated/torch.autograd.Function.forward.html

**Comment by Damowerko** [comment]
Reading the documentation that @bcharlier linked above, it seems like there might be an issue [here](https://github.com/getkeops/keops/blob/3eff8ea26a4d42b7738b137b004dcdea402b9063/pykeops/pykeops/torch/generic/generic_red.py#L153) if either `args` or `result` are tensors.

**Comment by joanglaunes** [comment]
Hello @Damowerko ,
Yes that is exactly the point ; we must use `ctx.save_for_forward()`. Actually I think in some previous versions of PyTorch this method was not available yet, although forward autodiff was already implemented, which is why we had to write it this way (see [here](https://discuss.pytorch.org/t/notimplementederror-you-must-implement-the-jvp-function-for-custom-autograd-function-to-use-it-with-forward-mode-ad/138245/2)). By the way, could you tell us which version of PyTorch you are using ?

**Comment by Damowerko** [comment]
I was using PyTorch 2.1, but I changed back to 2.0.

According to pytorch [docs](https://pytorch.org/docs/stable/notes/extending.func.html#limitations-and-gotchas): 

> Please only use [save_for_backward()](https://pytorch.org/docs/stable/generated/torch.autograd.function.FunctionCtx.save_for_backward.html#torch.autograd.function.FunctionCtx.save_for_backward) or save_for_forward() to save Tensors. Please do not assign Tensors or collections of Tensors directly onto the ctx object - these Tensors will not get tracked

I checked and `save_for_forward` was [added](https://github.com/pytorch/pytorch/pull/71569) in PyTorch 1.11.

I never used forward mode AD, but seemingly this can be resolved by using `ctx.save_for_backward(*args, result)` in `_setup_context` and then access them using `ctx.saved_tensors` in `jvp`.

**Comment by Damowerko** [comment]
Do have any tests for forward mode AD behaviour?

**Comment by joanglaunes** [comment]
I have done the modification in branch `issue_335_memLeaks`. I think it should fix the main problem, although apparently testing in google colab, there is still a small increase of memory after about 50 iterations with PyTorch >=2.0... Could you check it ? You can install this branch via
```shell
pip install git+https://github.com/getkeops/keops.git@issue_353_memLeaks#subdirectory=keopscore
pip install git+https://github.com/getkeops/keops.git@issue_353_memLeaks#subdirectory=pykeops
```

**Comment by bcharlier** [comment]
good on my side. I think we should require torch>=2.0 from now on...

**Comment by Damowerko** [comment]
Are there any tests that specifically check for forward mode AD?

**Comment by Damowerko** [comment]
In the application where I initially noticed the memory leak, my memory consumption is effectively constant after 10 minutes, whereas previously I would run out of memory within seconds.

**Comment by joanglaunes** [comment]
I have checked forward AD with this version on google colab, it's ok. The test script file  is `test_torch_func.py` in `pykeops/sandbox`, but I don't think we have put anything for forward AD in the automatic tests for CI. 
@bcharlier I'm not sure we should require PyTorch >= 2.0 already... Actually for example on my lab's server I have 1.13 and currently cannot upgrade because the drivers are too old and it's not that easy to get them updated! I'm thinking maybe other users could have similar problems.

**Comment by bcharlier** [comment]
@joanglaunes and @Damowerko : I added the tests for AD to the pykeops/test (run during CI) in commit eb311a60

**Comment by bcharlier** [comment]
Version v2.2.1 should fix the issue. Thank you everyone for your effort.
