### ISSUE TITLE
How to solve the problem of OsError？

### ISSUE THREAD

**Issue by Chris-Chengchen** [getkeops/keops#377]
OSError: /home/zcma02/.cache/keops2.2.3/Linux_server01_5.15.0-78-generic_p3.8.19/nvrtc_jit.so: cannot open shared object file: No such file or directory

**Comment by Chris-Chengchen** [comment]
No problem at first, when I restarted my computer this happened.

**Comment by P0lyFish** [comment]
I fixed this issue by explicitly set the CUDA_PATH variable:
```
export CUDA_PATH=/home/the.tran/.local/share/cuda-12.1
```

**Comment by the-king-of-yhq** [comment]
> No problem at first, when I restarted my computer this happened.
Can you solve this problem?
