### ISSUE TITLE
Triggering Explicit Computation After Pairwise Operations

### ISSUE THREAD

**Issue by adididi** [getkeops/keops#378]
Hello,

I am working on a problem where I need to perform pairwise operations along the last vector dimension (-1) and subsequently trigger **explicit computation**. My goal is to obtain a PyTorch matrix of shape `(M, N)` without applying any other reductions except summing over the vector (feature) dimension.

Here is a simplified version of my code:

```python
import torch
from pykeops.torch import LazyTensor

M = 1000
N = 2000
D = 10

x = torch.randn(M, D)  # M target points in dimension D
y = torch.randn(N, D)  # N source points in dimension D

x_i = LazyTensor(x[:, None, :])  # (M, 1, D) LazyTensor
y_j = LazyTensor(y[None, :, :])  # (1, N, D) LazyTensor

D_ij = ((x_i - y_j) ** 2).sum(-1)  # Symbolic (M, N) matrix of squared distances

print(f"D_ij is now a {type(D_ij)} with shape {D_ij.shape}.")
```

The matrix `D_ij` is currently a symbolic LazyTensor representing the squared distances between points in `x` and `y`. I want to explicitly compute `D_ij` to obtain a `(M, N)` pytorch matrix.

Could you please advise on how I can achieve this ? Any guidance or suggestions would be greatly appreciated.

Thank you!

**Comment by jeanfeydy** [comment]
Hi @adididi ,

Thanks for your interest in our library.
Unfortunately, KeOps does not currently support this feature: our engine is centered around reductions of distance-like matrices and is not designed to create efficiently large N-by-M dense arrays. The best thing you can do here is probably to expand your squared distance and compute the full distance matrix with a matmul.

Best regards,
Jean
