### ISSUE TITLE
Pykeops set verbose and build_type from environment variable

### ISSUE THREAD

**Issue by benoitmartin88** [getkeops/keops#4]
Hi,

It would be great if PyKeops could be set to verbose and/or debug using environment variables instead of editing the `__init__.py` file.

```
verbose = False  # display output of compilations
build_type = "Release"  # 'Release' or 'Debug'
```

**Comment by bcharlier** [comment]
When doing 

`import pykeops`

it now checks the existence of an environment variable KEOPS_VERBOSE (which should be an integer 0 or 1) to set verbosity flag. If the env variable does not exist verbosity is set to False.

**Comment by benoitmartin88** [comment]
Thank you ! This is great
Would it also be possible to change the `build_type ` from an environment variable ? Something like `KEOPS_BUILD_TYPE` ?
