### ISSUE TITLE
Why does PyKeOps require GCC >= 7 ?

### ISSUE THREAD

**Issue by samfux84** [getkeops/keops#42]
Hi,

The installation instructions for PyKeOps lists the following requirements:

A C++ compiler compatible with std=c++14: g++ version >=7 or clang++ version >=8.

But according to the GCC website

https://gcc.gnu.org/projects/cxx-status.html

already the GCC versions 5.x and 6.x should fully implement c++14. Should it therefore be possible to install PyKeOps already with GCC 6.3.0 ? Or is there another reason that you ask for GCC >= 7 ? This version would already fully implement c++17.

Best regards

Sam

**Comment by bcharlier** [comment]
Hi @samfux84 ,

short answer : We perform our CI with gcc==7 or 8... and we don't have CI runner with older gcc. That is the reason why we put this as a requirement. Sorry.

Long answer: you're perfectly right as PyKeop just need --std=c++14. It works with gcc5.4 (issue #37 ) on some system. The trick is that you need a version of gcc that is compliant with your nvcc and the pyTorch headers (if you use pytorch bindings).

b.

**Comment by samfux84** [comment]
@bcharlier ,

Thank you for your reply. I can fully understand that you cannot test dozens of compiler versions and therefore put a focus on the newer versions.

Still, this is good news for me. I got a request to install PyKeOps on our cluster. For the GCC 6.3.0 toolchain I already have a recent Python 3.7.4, whereas I don't have this yet for our GCC 8.2.0 toolchain. Therefore being able to use GCC 6.3.0 does save me quite some work.

Best regards and again thank you for your help.
