### ISSUE TITLE
Impossible to install RKeops 

### ISSUE THREAD

**Issue by AnthoOzier** [getkeops/keops#50]
When I try 
`install.packages("rkeops")`
I get 
```
Warning in install.packages :
  package ‘rkeops’ is not available (for R version 3.6.2) 
```

When I try 
`devtools::install_git("https://github.com/getkeops/keops",
                       subdir = "rkeops",
                       args="--recurse-submodules='keops/lib/sequences'")`
I get 
```
Erreur : Failed to install 'unknown package' from Git:
  Error in 'git2r_remote_ls': there is no TLS stream available
```

I'm running R3.6.2 on Ubuntu 18.04.4  : 
```
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.2                         
year           2019                        
month          12                          
day            12                          
svn rev        77560                       
language       R                           
version.string R version 3.6.2 (2019-12-12)
nickname       Dark and Stormy Night 
```

Any idea on the origin of the problem ?

**Comment by gdurif** [comment]
Hi,
Sorry the install from CRAN is not working yet. I anticipated too much when writing the doc.

Regarding the install from github, I am running some tests. Is your version of 'devtools' up-t-date?

In the mean time, could you try the install from local git repository? (see https://www.kernel-operations.io/keops/R/using_rkeops.html)
Thanks

**Comment by gdurif** [comment]
I forgot, maybe you have some issues with R package `devtools` which requires some Ubunto package dependencies, see https://www.digitalocean.com/community/tutorials/how-to-install-r-packages-using-devtools-on-ubuntu-18-04

**Comment by gdurif** [comment]
There was an issue with the `devtools` command, please use
```R
devtools::install_git("https://github.com/getkeops/keops", 
                      subdir = "rkeops", 
                      args="--recursive")
```

**Comment by AnthoOzier** [comment]
Hello, 
I finally decided to use Pykeops instead of Rkeops. 
But I installed Rkeops in case I want to go back to it later. 
The `devtools` command still gives the same error output : 
``` 
devtools::install_git("https://github.com/getkeops/keops", 
                      subdir = "rkeops", 
                      args="--recursive")
```
```
Erreur : Failed to install 'unknown package' from Git:
  Error in 'git2r_remote_ls': there is no TLS stream available
```
But I was able to install rkeops version 1.3 from local git repository using `git clone`. 
Thanks for your help.

**Comment by bcharlier** [comment]
Hi @AnthoOzier ,

FYI rkeops is now available on the CRAN:
```
install.packages("rkeops")
```
is working on my system. Feel free to reopen the issue if you experience problems when installing `rkeops`...
