### ISSUE TITLE
Shared object compiled without CUDA support

### ISSUE THREAD

**Issue by Veason-silverbullet** [getkeops/keops#53]
Hi, teams! I met an issue in the test sample

![issue](https://user-images.githubusercontent.com/46241015/75958201-afa4cb80-5ef6-11ea-9068-aef6888fd099.png)

My compiling configuration is

g++ Version: 7.3.0
gcc Version: 7.3.0
cmake Version: 3.14.0
nvcc Version: 10.0.130
Nvidia Driver Version: 440.64
CUDA Version: 10.1
Pytorch Version: 1.3.1

Many thanks!

**Comment by Veason-silverbullet** [comment]
Problem solved.

**Comment by atechnicolorskye** [comment]
@Veason-silverbullet @fradav I have the same problem. How did you fix it?

**Comment by Veason-silverbullet** [comment]
@atechnicolorskye I used the source code to compile and solved it by two steps.
1. Check the keops/cuda.cmake. Make sure the variable 'USE_CUDA' to be true. I modified the script in 'find_package' function to make Cmake find the proper path of CUDA lib. I think the issue came from Anaconda, which hid from the CUDA lib. 
2. Make sure '-std=c++14' in 'CXXFLAGS'. c++17 is not compatible.

**Comment by bcharlier** [comment]
You can avoid to modify anything in the CMake scripts. The `find_package(cuda)` of CMake is basically looking for `/usr/local/cuda`. You can create a symlink pointing to where your cuda is installed. You can also use venvs.

**Comment by jeanfeydy** [comment]
Hi @atechnicolorskye ,

I assume that you solved the problem on your machine and am closing the issue. Feel free to re-open it if needed!

Best regards,
Jean
