### ISSUE TITLE
Eigen Values and eigen vectors with keops

### ISSUE THREAD

**Issue by AnthoOzier** [getkeops/keops#54]
I would like to implement a formula that involve eigen values and eigen vectors of the gram matrix. Do you think its possible to compute it with keops (e.g. using the KernelSolve) or not?

**Comment by jeanfeydy** [comment]
Hi @AnthoOzier ,

Sure! As of today, the best way of computing the eigenvalues/vectors of a KeOps LazyTensor is probably to use the standard scipy solvers as described in [this tutorial](http://www.kernel-operations.io/keops/_auto_tutorials/backends/plot_scipy.html). In practice, you could use a code along the lines of:

```python
# Setup:
import numpy as np
from pykeops.numpy import LazyTensor
from pykeops.numpy.utils import IsGpuAvailable

use_cuda = IsGpuAvailable()
dtype = "float32"  # No need for double precision here!


# Create a large Gram matrix:
N = 10000 if use_cuda else 1000
D = 10

x = np.random.randn(N, D).astype(dtype)
x_i, x_j = LazyTensor(x[:, None, :]), LazyTensor(x[None, :, :])
G_ij = (x_i | x_j)  # Symbolic (N,N) Gram matrix


# Use the SciPy solver to compute its eigenvalues:
from scipy.sparse.linalg import aslinearoperator, eigsh

G = aslinearoperator(G_ij)
eigenvalues, eigenvectors = eigsh(G, k=5)  # Largest 5 eigenvalues/vectors

print("Largest eigenvalues:", eigenvalues)
print("Eigenvectors of shape:", eigenvectors.shape)
```


Long-term, these features may be supported through a full-Pytorch, full-GPU, differentiable interface: we'd need a good collection of black-box linear solvers implemented in Pytorch or any other modern framework. As of today, your best bet may be to look at the [GPytorch](https://gpytorch.ai/) library, as discussed in the twin tutorials from the [KeOps](http://www.kernel-operations.io/keops/_auto_tutorials/backends/plot_gpytorch.html) and [GPytorch](https://gpytorch.readthedocs.io/en/latest/examples/02_Scalable_Exact_GPs/KeOps_GP_Regression.html) documentation.

Best regards,
Jean
