### ISSUE TITLE
Kernel with norm matrix indexed by i and j

### ISSUE THREAD

**Issue by adam-coogan** [getkeops/keops#55]
Hi! I am trying to figure out how to construct a kernel where the matrix defining the norm has `i` and `j` indices. More specifically, I want the kernel evaluated at the points `x_i` and `y_j` to be
```
k(x_i, y_j) = exp(-1/2 d_ij @ inverse(S_i + S_j) @ d_ij) / sqrt(det(S_i + S_j)),
d_ij = x_i - y_j.
```
For my specific problem, `x_i` and `y_i` are vectors of length `d=2`. I want to use `k` with `KernelSolve`, and I need to use the pytorch backend and to be able to take gradients.

I was wondering how to best do this in keops. Since `d` is 2, I can write out explicit expressions for everything in terms of the components of the vectors and elements of the matrices `S_i` and `S_j`. However, this could be optimized substantially by only computing `det(S_i + S_j)` once for each `(i, j)`. Is there any way I can write formulas like this, or would it require something lower-level in keops? Thanks!

For reference, here's how I'm constructing the kernel and solver now:
```python
d_0 = "(Elem(x_i, 0) - Elem(y_j, 0))"
d_1 = "(Elem(x_i, 1) - Elem(y_j, 1))"
s_00 = "(Elem(s_i, 0) + Elem(s_j, 0))"
s_01 = "(Elem(s_i, 1) + Elem(s_j, 1))"
s_11 = "(Elem(s_i, 3) + Elem(s_j, 3))"
det = f"({s_00} * {s_11} - Square({s_01}))"
s_inv_00 = f"({s_11} / {det})"
s_inv_01 = f"(-{s_01} / {det})"
s_inv_11 = f"({s_00} / {det})"
formula = (
    "Exp(-("
    f"Square({d_0}) * {s_inv_00} + "
    f"IntCst(2) * {d_0} * {d_1} * {s_inv_01} +"
    f"Square({d_1}) * {s_inv_11}"
    ") * IntInv(2))"
    f" * alpha2 * Rsqrt({det}) * theta_j"
)

aliases = [
    "x_i = Vi(2)",
    "y_j = Vj(2)",
    "s_i = Vi(4)",
    "s_j = Vj(4)",
    "alpha2 = Pm(1)",
    "theta_j = Vj(1)"
]

K = Genred(formula, aliases, axis=1)
K_inv = KernelSolve(formula, aliases, "theta_j", axis=1)
```

**Comment by adam-coogan** [comment]
So, I originally thought the determinant expression was being recomputed multiple times since it appears five times in the formula. However, I’ve done some more careful testing by removing the determinant from the expression and found only a marginal speedup. I guess I was forgetting that the CUDA compiler optimizes formulas once they’re converted to C code. 

Unless I'm missing some other way this could be sped up substantially, I'll close the issue.

**Comment by bcharlier** [comment]
Hi @adam-coogan ,

yes you're right. I put @joanglaunes  in the loop. As far as I know; during compile time:
- we factorize the formula (meaning that a chunk of formula needed multiple time is indeed compute only once). see [this file](https://github.com/getkeops/keops/blob/master/keops/core/formulas/Factorize.h)
- the compiler itself is doing theses kinds of optimization

In french we say '[mettre la ceinture et les bretelles'](https://www.wordreference.com/fren/mettre%20la%20ceinture%20et%20les%20bretelles)...

b.

**Comment by joanglaunes** [comment]
Hello @adam-coogan and @bcharlier ,
In fact there is a AutoFactorize operation in the C++ part of KeOps, that detects similar expressions and applies Factorize automatically, but it is not activated by default, because it slows down the compile time a lot in some cases. 
But as Benjamin says, is is very likely that the compiler does the factorization itself, so that would be the reason in your case.
Joan
