### ISSUE TITLE
Prebuilt binaries do not work with pytorch v1.5.0

### ISSUE THREAD

**Issue by keckj** [getkeops/keops#59]
Torch 1.5.0 has been released four days ago and breaks the installation of pykeops using pip.

The following commands install pykeops using pip
```
pip3.6 install pykeops
pip3.7 install pykeops
pip3.8 install pykeops
```
but yield the same error on module import for every python version I tried.

This seems to be linked to a change of interface in the torch library:
```pykeops-1.4-cpython-38/libKeOpstorch4770b04be2.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE```

A simple temporary fix is to downgrade the version of torch manually using `pip3 install --upgrade pykeops torch==1.4.0`

**Comment by neel-dey** [comment]
Ran into this myself and can confirm that just downgrading to PyTorch 1.4 seems to resolve it. Full stacktrace with 1.5 in a conda environment:

`pykeops.test_torch_bindings()                                                                                                                                                                       
Compiling libKeOpstorch13367cc0e8 in /home/neel/.cache/pykeops-1.4-cpython-38/build-libKeOpstorch13367cc0e8:
       formula: Sum_Reduction(SqNorm2(x - y),1)
       aliases: x = Vi(0,3); y = Vj(1,3); 
       dtype  : float32
... Generated /home/neel/.cache/pykeops-1.4-cpython-38/build-libKeOpstorch13367cc0e8/CMakeFiles/keopslibKeOpstorch13367cc0e8.dir/keops/core/./keopslibKeOpstorch13367cc0e8_generated_link_autodiff.cu.o successfully.
Done.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/anaconda3/envs/geomloss/lib/python3.8/site-packages/pykeops/test/install.py in test_torch_bindings()
     54     my_conv = pktorch.Genred(formula, var)
---> 55     if torch.allclose(my_conv(x, y).view(-1), torch.tensor(expected_res).type(torch.float32)):
     56       print("\npyKeOps with torch bindings is working!\n")

~/anaconda3/envs/geomloss/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.py in __call__(self, backend, device_id, ranges, *args)
    394 
--> 395         out = GenredAutograd.apply(self.formula, self.aliases, backend, self.dtype, 
    396                                    device_id, ranges, self.accuracy_flags, *args)

~/anaconda3/envs/geomloss/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.py in forward(ctx, formula, aliases, backend, dtype, device_id, ranges, accuracy_flags, *args)
     21 
---> 22         myconv = LoadKeOps(formula, aliases, dtype, 'torch', optional_flags).import_module()
     23 

~/anaconda3/envs/geomloss/lib/python3.8/site-packages/pykeops/common/keops_io.py in import_module(self)
     51     def import_module(self):
---> 52         return importlib.import_module(self.dll_name)

~/anaconda3/envs/geomloss/lib/python3.8/importlib/__init__.py in import_module(name, package)
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 

~/anaconda3/envs/geomloss/lib/python3.8/importlib/_bootstrap.py in _gcd_import(name, package, level)

~/anaconda3/envs/geomloss/lib/python3.8/importlib/_bootstrap.py in _find_and_load(name, import_)

~/anaconda3/envs/geomloss/lib/python3.8/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

~/anaconda3/envs/geomloss/lib/python3.8/importlib/_bootstrap.py in _load_unlocked(spec)

~/anaconda3/envs/geomloss/lib/python3.8/importlib/_bootstrap.py in module_from_spec(spec)

~/anaconda3/envs/geomloss/lib/python3.8/importlib/_bootstrap_external.py in create_module(self, spec)

~/anaconda3/envs/geomloss/lib/python3.8/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: /home/neel/.cache/pykeops-1.4-cpython-38/libKeOpstorch13367cc0e8.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-8-6a85b86e8570> in <module>
----> 1 pykeops.test_torch_bindings()

~/anaconda3/envs/geomloss/lib/python3.8/site-packages/pykeops/test/install.py in test_torch_bindings()
     64     pykeops.build_type = "Debug"
     65     my_conv = pktorch.Genred(formula, var)
---> 66     print(my_conv(x, y))
     67 

~/anaconda3/envs/geomloss/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.py in __call__(self, backend, device_id, ranges, *args)
    393             args, ranges, tag_dummy, N = preprocess_half2(args, self.aliases, self.axis, ranges, nx, ny)
    394 
--> 395         out = GenredAutograd.apply(self.formula, self.aliases, backend, self.dtype, 
    396                                    device_id, ranges, self.accuracy_flags, *args)
    397 

~/anaconda3/envs/geomloss/lib/python3.8/site-packages/pykeops/torch/generic/generic_red.py in forward(ctx, formula, aliases, backend, dtype, device_id, ranges, accuracy_flags, *args)
     20         optional_flags = ['-D_GLIBCXX_USE_CXX11_ABI=' + str(int(torch_cxx11_abi_flag)), '-DPYTORCH_INCLUDE_DIR=' + ';'.join(include_dirs)] + accuracy_flags
     21 
---> 22         myconv = LoadKeOps(formula, aliases, dtype, 'torch', optional_flags).import_module()
     23 
     24         # Context variables: save everything to compute the gradient:

~/anaconda3/envs/geomloss/lib/python3.8/site-packages/pykeops/common/keops_io.py in import_module(self)
     50 
     51     def import_module(self):
---> 52         return importlib.import_module(self.dll_name)

~/anaconda3/envs/geomloss/lib/python3.8/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

~/anaconda3/envs/geomloss/lib/python3.8/importlib/_bootstrap.py in _gcd_import(name, package, level)

~/anaconda3/envs/geomloss/lib/python3.8/importlib/_bootstrap.py in _find_and_load(name, import_)

~/anaconda3/envs/geomloss/lib/python3.8/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

~/anaconda3/envs/geomloss/lib/python3.8/importlib/_bootstrap.py in _load_unlocked(spec)

~/anaconda3/envs/geomloss/lib/python3.8/importlib/_bootstrap.py in module_from_spec(spec)

~/anaconda3/envs/geomloss/lib/python3.8/importlib/_bootstrap_external.py in create_module(self, spec)

~/anaconda3/envs/geomloss/lib/python3.8/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: /home/neel/.cache/pykeops-1.4-cpython-38/libKeOpstorch13367cc0e8.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE`

**Comment by bcharlier** [comment]
Hi all,

well, same problem on my system. Pytorch C++ frontend has moved a lot between 1.4 and 1.5...

I am able to resolve the c10::AutogradMetaInterface missing symbol appearing in @neel-dey message by linking to the proper shared object. Unfortunately, another missing symbol pops up : THPVariableClass. 

I am stuck with that. I keep working on it...

**Comment by bcharlier** [comment]
Hi, 

for some reasons, there are symbols that are not exposed in the binary shipped by pytorch v1.5.0 linux (as far as I know, the problem does not affect macOS version). 

For now, a simple workaround is to set the environment variable `TORCH_USE_RTLD_GLOBAL=YES`. Namely run 

```bash
$ TORCH_USE_RTLD_GLOBAL=YES python 
```
or 

```bash
$ export TORCH_USE_RTLD_GLOBAL=YES
$ python
```
or

```bash
$ echo "export TORCH_USE_RTLD_GLOBAL=YES" >> ~/.bashrc
```
or 
...

I hope the pytorch package will be updated soon to avoid declaring the variable every time...

**Comment by neel-dey** [comment]
Thanks for looking into this @bcharlier!

**Comment by parthe** [comment]
@bcharlier This didn't seem to work. I am using the following installation test in a jupyter notebook after running TORCH_USE_RTLD_GLOBAL=YES.
`import pykeops
pykeops.clean_pykeops()          # just in case old build files are still present
pykeops.test_torch_bindings()    # perform the compilation`
I continue to get the same error. Can you briefly explain what the RTLD_GLOBAL flag does?

**Comment by jeanfeydy** [comment]
Hi @parthe (@bcharlier is currently offline on vacations),

How did you set the environment variable `TORCH_USE_RTLD_GLOBAL`? In a jupyter notebook, the [recommended methods](https://stackoverflow.com/questions/37890898/how-to-set-env-variable-in-jupyter-notebook) seem to rely on the `%env` command or on the `kernel.json` file. As of today, the code snippet below works fine in a fresh Google Colab session:

```python
!pip install pykeops[full] > log.txt

%env TORCH_USE_RTLD_GLOBAL=YES

import pykeops
pykeops.clean_pykeops()
pykeops.test_torch_bindings()
```

Does it solve your problem?
Best regards,

Jean

**Comment by parthe** [comment]
@jeanfeydy, It worked for me
Thanks a lot! I was not aware of this magic command.

**Comment by jeanfeydy** [comment]
The v1.4.1 release (31a7852) finally pushes this fix onto the "pip" repository.
