### ISSUE TITLE
pybind11 does not find python interpreter if not present in system path

### ISSUE THREAD

**Issue by Poulpy21** [getkeops/keops#60]
This issue is similar to issue #49, but this time the shipped CMakeLists.txt does not find the python interpreter even if the version is supplied. At some point pybind11 invokes `FindPythonInterp.cmake` which fails because `PYTHON_EXECUTABLE` has not been defined and no matching python executable can be found in system path.

As the path to the running python interpreter can be obtained with `sys.executable`, a simple fix consists into inserting `'-DPYTHON_EXECUTABLE=' + sys.executable,` to `pykeops/common/compile_routines.py:54`.

```diff
--- compile_routines.py	2020-05-05 13:47:43.688013050 +0000
+++ compile_routines.py	2020-05-05 13:48:17.340202073 +0000
@@ -51,6 +51,7 @@
                      '-Dshared_obj_name=' + dllname,
                      '-D__TYPE__=' + c_type[dtype],
                      '-DPYTHON_LANG=' + lang,
+                     '-DPYTHON_EXECUTABLE=' + sys.executable,
                      '-DPYBIND11_PYTHON_VERSION=' + str(sys.version_info.major) + '.' +str(sys.version_info.minor),
                      '-DC_CONTIGUOUS=1',
                     ] + optional_flags

```

**Comment by bcharlier** [comment]
thank @Poulpy21 , included in commit c7f7f0aa5a9174cdb1adafaa7b1f6ddddfe33d86.
Do not hesitate to PR for this kind of issue.

b.
