### ISSUE TITLE
Batched knn

### ISSUE THREAD

**Issue by zawlin** [getkeops/keops#73]
I am currently looking into implementing unstructured interpolation using inverse distance weighting for 3d points. I did some preliminary tests and found that keops can do brute force nearest neighbours at the speed that is required by my application. But I need to integrate this into a pytorch training pipeline which would include batches of 3d points. I was wondering how I can do batch-based nearest neighbour? Let's say I have 8x10000 reference points and 8x20000 query points. I would like a result of 8x3x20000(ikN) top 3 distances each ith index corresponding to the i-th source and query pairs. Its not super clear to me how this can be done. Is there an example of use case that I can refer to? I am looking for something like this example(https://www.kernel-operations.io/keops/_auto_examples/numpy/plot_test_ArgKMin.html) but that can operate on batches of source and query pairs. Thanks!

**Comment by jeanfeydy** [comment]
Hi @zawlin ,

Thanks a lot for your interesting question! First of all, all my apologies for this late reply: we have been extremely busy over the last two months and are just starting to catch up on late issues.

To answer your question: KeOps supports batch computations using **standard broadcasting syntax**, as well as a more advanced mode for **heterogeneous situations** when the clouds don't have the exact same number of points - this is typical in shape analysis.

As a quick example, let's assume that your data is generated with:

```python
import torch
from pykeops.torch import LazyTensor
torch.set_default_tensor_type(torch.cuda.FloatTensor)

# Toy input data:
B, N, M = 8, 20000, 10000  # Batchsize, query points, reference points
D, K = 3, 5  # Dimension, number of neighbors
x, y = torch.randn(B, N, D), torch.randn(B, M, D)
```

Then, with PyTorch vanilla, the standard way of computing a batched K-NN search is to use:

```python
# Reshape the tensors to use broadcasting syntax:
x_i = x.view(B, N, 1, D)
y_j = y.view(B, 1, M, D)

# Dense matrix of squared distances:
D_ij = ((x_i - y_j) ** 2).sum(-1)  # (B, N, M)

# Batched K-NN search with PyTorch:
indices_i = D_ij.topk(K, dim=2, largest=False).indices
```

KeOps lets you perform the same computation faster and with a (much) lower memory footprint: you just have to turn your point clouds into symbolic LazyTensors before creating the matrix of squared distances.

```python
# Turn our tensors into KeOps symbolic variables:
x_i = LazyTensor( x.view(B, N, 1, D) )
y_j = LazyTensor( y.view(B, 1, M, D) )

# Symbolic matrix of squared distances:
D_ij = ((x_i - y_j) ** 2).sum(-1)  # (B, N, M)

# Batched K-NN search with KeOps:
indices_i = D_ij.argKmin(K, dim=2)
```

Going further, the advanced `.ranges` attribute lets you work with more general configurations. The precise syntax is discussed in [this page of the documentation](http://www.kernel-operations.io/keops/python/sparsity.html) as well as [this tutorial](http://www.kernel-operations.io/keops/_auto_examples/pytorch/plot_grid_cluster_pytorch.html) and the [API doc](http://www.kernel-operations.io/keops/python/api/pytorch/Genred_torch.html#pykeops.torch.Genred.__call__) with [helper routines](http://www.kernel-operations.io/keops/python/api/pytorch/Cluster.html).

In the example below, I detail how to interface KeOps with the ["batch vector" syntax](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#mini-batches) used by [PyTorch_geometric](https://pytorch-geometric.readthedocs.io/):

```python
def ranges_slices(batch):
    """Helper function for the diagonal ranges function."""
    Ns = batch.bincount()
    indices = Ns.cumsum(0)
    ranges = torch.cat((0 * indices[:1], indices))
    ranges = torch.stack((ranges[:-1], ranges[1:])).t().int().contiguous().to(batch.device)
    slices = (1 + torch.arange(len(Ns))).int().to(batch.device)
    
    return ranges, slices


def diagonal_ranges(batch_x = None, batch_y = None):
    """Encodes the block-diagonal structure associated to a batch vector."""
    
    if batch_x is None and batch_y is None: return None
    
    ranges_x, slices_x = ranges_slices(batch_x)
    ranges_y, slices_y = ranges_slices(batch_y)
    
    return ranges_x, slices_x, ranges_y, ranges_y, slices_y, ranges_x 


# Stacked encoding for heterogeneous batch processing:
x, y = x.view(B*N, D), y.view(B*M, D)

# Batch vectors - must be of the form:
# [0, ..., 0, 1, ..., 1, ..., B-1, ..., B-1]
# with an arbitrary number of points per cloud.
# Here, we use a uniform choice (N points per cloud)
# that corresponds to the standard, uniform batch behavior
# of the previous examples.
batch_x = torch.arange(B).view(B, 1).repeat(1, N).view(B*N)
batch_y = torch.arange(B).view(B, 1).repeat(1, M).view(B*M)

# Symbolic matrix of squared distances:
x_i = LazyTensor(x[:,None,:])    # (B*N, 1, D)
y_j = LazyTensor(y[None,:,:])    # (1, B*M, D)
D_ij = ((x_i - y_j)**2).sum(-1)  # (B*N, B*M)
    
# Apply a block-diagonal sparsity mask:
D_ij.ranges = diagonal_ranges(batch_x, batch_y)

# K-NN search with heterogeneous batches:
indices_i = D_ij.argKmin(K, dim=1)  # (B*N, K)
```

Note that the indices above range in `[0, B*M[`, which is fine in most use cases.
To retrieve indices in `[0, M[`, don't forget to offset the values as follows:
```python
Ns = batch_y.bincount()     # (B,), number of points per cloud
indices = Ns.cumsum(0)      # (B,)
indices = torch.cat((0 * indices[:1], indices[:-1]))
offsets = indices[batch_x]  # (B*N,)
indices_i = indices_i - offsets[:,None]
```

Going forward, we will probably include the `diagonal_ranges` helper directly in the main KeOps repository. LazyTensors could also accept directly a `.batch` attribute, for easier integration with e.g. PyTorch_Geometric: this is something that I will discuss soon with @rusty1s and that will be integrated in future releases.

I hope that this answers your question! If you need anything else, feel free to re-open the issue.
Best regards,
Jean
