### ISSUE TITLE
LogSumExpWeight for LazyTensor where vector gets exponentiated

### ISSUE THREAD

**Issue by zsteve** [getkeops/keops#76]
Hi, I'm trying to use the LazyTensor API to compute the following reduction:

```u = log(K * exp(v))```

where:
 * `u, v` are N-dimensional vectors
 *  `K` is a (N, N) LazyTensor.

I thought this looked like something that LogSumExpWeight from the API could handle, but from what I understand after reading the documentation, the expression above doesn't seem to fit in the framework. 
Specifically, in LogSumExpWeight, the LazyTensor is exponentiated while an additional weight argument is supplied. Conversely, here I need the LazyTensor `K` to be the weights, and `v` an ordinary vector to be exponentiated.

Is this a functionality that is already implemented as part of the LazyTensor API? Perhaps I have missed something :)

Thanks!

**Comment by jeanfeydy** [comment]
Hi @zsteve ,

Thanks for your interest in the library! As far as I can tell, the simplest way of computing your reduction is to express it as a **log-sum-exp reduction of the LazyTensor `K.log() + v`**.

For instance, if K is a [Cauchy kernel matrix](https://en.wikipedia.org/wiki/Cauchy_distribution), the following code should do the trick:

```python
import torch
from pykeops.torch import LazyTensor
if torch.cuda.is_available(): torch.set_default_tensor_type(torch.cuda.FloatTensor)

N, D =  100000, 10
x, v = torch.randn(N, D), torch.randn(N)

# Create a symbolic Cauchy kernel matrix:
x_i = LazyTensor( x.view(N, 1, D) )
x_j = LazyTensor( x.view(1, N, D) )

D_ij = ( (x_i - x_j) ** 2).sum(-1)  # (N, N, 1) matrix of squared distances
K_ij = 1 / (1 + D_ij)

# Wrap v as a "column" j variable:
v_j = LazyTensor( v.view(1, N, 1) )

# Perform the reduction:
u_i = (K_ij.log() + v_j).logsumexp(dim=1).view(-1)  # (N,) PyTorch vector
```

Going further, if your kernel matrix has a specific form, simplifying `K_ij.log()` by hand could be more efficient: this is typically the case  if K is a Gaussian or Exponential kernel matrix, as encountered e.g. in the Sinkhorn algorithm for optimal transport.
Does this answer your question?

Best regards,
Jean

**Comment by joanglaunes** [comment]
Hello @zsteve ,
In addtion, in fact the LogSumExpWeight reduction can perfectly be used here also : you can replace the last line of Jean's code snippet by
```python
u_i = v_j.logsumexp(dim=1,weight=K_ij).view(-1)
```
It will compute the same.

Best,
Joan

**Comment by jeanfeydy** [comment]
Indeed @joanglaunes , 

I had forgotten that you had fully implemented the `LazyTensor` interface!
Note however that for applications to entropic optimal transport, where `K_ij = (-C_ij / epsilon).exp()` is the Gibbs kernel matrix associated to a cost function `C_ij = C(x_i,y_j)` at temperature `epsilon`, performing the reduction as:

```python
# Perform the reduction:
u_i = (- C_ij / epsilon + v_j).logsumexp(dim=1).view(-1)  # (N,) PyTorch vector
```
will avoid the "compression" of `K_ij` as a float32 number and therefore be much more stable numerically. 
I stress it as this could be relevant to @zsteve .

Best regards,
Jean

**Comment by zsteve** [comment]
Many thanks @jeanfeydy  and @joanglaunes, this is perfect! I think what I was really missing was that I could wrap a column vector as a `LazyTensor`. 

> P.S.: I just remarked that you are from UBC, so you certainly know Hugo Lavenant! If you're interested in large-scale OT, you may want to have a look at Chapters 3-4 of my PhD thesis: I discussed these solvers fairly extensively in Section 3.3.

Yes I actually work with Hugo! Thanks for the pointer, I will give it a read :)

Thanks again for the help,
Stephen

**Comment by jeanfeydy** [comment]
You're welcome - and good luck!

Best regards,
Jean
