### ISSUE TITLE
Error multipying a LazyTensor with a "raw" PyTorch tensor of real data!

### ISSUE THREAD

**Issue by arahiche** [getkeops/keops#82]
Hello, 
Many thanks for your amazing project!

I am trying to perform a simple multiplication between two tensors, a LazyTensor and a PyTorch tensor. The script compiles well if my variables are generated randomly, however, it fails with real data loaded from a .mat file.

Here is my code with random initialization:

```python
dtype = torch.cuda.FloatTensor if use_cuda else torch.FloatTensor
D = 10
M = 100000
N = 200000
x = torch.randn(M, D).type(dtype)  
y = torch.randn(N, D).type(dtype)  
x_i = LazyTensor(x[:, None, :])  # (M, 1, D) LazyTensor
y_j = LazyTensor(y[None, :, :])  # (1, N, D) LazyTensor
D_ij = ((x_i - y_j) ** 2).sum(-1)   # Symbolic (M, N) matrix
K_ij = (- D_ij).exp()  # Symbolic (M, N) kernel matrix
b = torch.randn(K_ij.shape[1], D).type(dtype)
a_i = K_ij @ b
```

Here is the same code but with real data:

```python
data = io.loadmat('a0.mat')['avg']
data = torch.from_numpy(data).type(dtype)
x_i = LazyTensor( data[:, None, :] )  
y_j = LazyTensor( data[None, :, :] )  
D_ij = ((x_i - y_j)**2).sum(-1)  # Symbolic matrix
K_ij = (- D_ij).exp()               # Symbolic Gaussian kernel matrix
b = torch.randn(K_ij.shape[1], 10).type(dtype)
a_i = K_ij @ b
```

Here is the error I got:

>a_i = K_ij @ b 
  File "/home/xxxxx/anaconda2/envs/py3dev/lib/python3.7/site-packages/pykeops-1.4.1-py3.7.egg/pykeops/common/lazy_tensor.py", line 1779, in __matmul__
    Kv = Kv.sum( Kv.dim() - 2 )  # Matrix-vector or Matrix-matrix product
  File "/home/xxxxx/anaconda2/envs/py3dev/lib/python3.7/site-packages/pykeops-1.4.1-py3.7.egg/pykeops/common/lazy_tensor.py", line 1360, in sum
    return self.reduction("Sum", axis=axis, **kwargs)
  File "/home/xxxxx/anaconda2/envs/py3dev/lib/python3.7/site-packages/pykeops-1.4.1-py3.7.egg/pykeops/common/lazy_tensor.py", line 560, in reduction
    return res()
  File "/home/xxxxx/anaconda2/envs/py3dev/lib/python3.7/site-packages/pykeops-1.4.1-py3.7.egg/pykeops/common/lazy_tensor.py", line 716, in __call__
    return self.callfun(*args, *self.variables, **self.kwargs)
  File "/home/xxxxx/anaconda2/envs/py3dev/lib/python3.7/site-packages/pykeops-1.4.1-py3.7.egg/pykeops/torch/generic/generic_red.py", line 396, in __call__
    device_id, ranges, self.accuracy_flags, *args)
  File "/home/xxxxx/anaconda2/envs/py3dev/lib/python3.7/site-packages/pykeops-1.4.1-py3.7.egg/pykeops/torch/generic/generic_red.py", line 44, in forward
    result = myconv.genred_pytorch(tagCPUGPU, tag1D2D, tagHostDevice, device_id, ranges, *args)
RuntimeError: [Keops] Arg at position 0: is not contiguous. Please provide 'contiguous' dara array, as KeOps does not support strides. If you're getting this error in the 'backward' pass of a code using torch.sum() on the output of a KeOps routine, you should consider replacing 'a.sum()' with 'torch.dot(a.view(-1), torch.ones_like(a).view(-1))'. 

I tried to force the LazyTensor to be contiguous but I got an error 
>AttributeError: 'LazyTensor' object has no attribute 'contiguous'

Any help on how to solve this problem?

**Comment by arahiche** [comment]
I solved the issue. I forced the pytorch tensor itself to be a contiguous tensor not the resulted keops tensor, so I used instead

   data = torch.from_numpy(data).contiguous().type(dtype)

**Comment by arahiche** [comment]
I solved the issue. I forced the pytorch tensor itself to be a contiguous tensor not the resulted LazyTensor, so I used instead

>data = torch.from_numpy(data).contiguous().type(dtype)

However, I have another problem now. I need to keep >a_i as a pytorch tensor for further processing, but in case the >b variable is large the multiplication will raise a memory issue. 

Is there any why to convert a LazyTensor to a torch, so I can perform a LazyTensors multiplication then convert the result into a torch tensor?

**Comment by jeanfeydy** [comment]
Hi @arahiche ,

Thanks for your kind comments!
Your first problem was due to the **different conventions between Matlab and Python** for array storage: by default, Matlab uses column-major ordering (Fortran-contiguous convention), whereas Numpy and PyTorch rely on row-major ordering (C-contiguous convention). The second encoding is coherent with the common convention in data sciences: rows correspond to samples and columns to features. 
It is the expected input format for KeOps: thanks to the `.contiguous()` method, you could re-order your arrays to make sure that all the coordinates of a given vector/sample/point are stored next to each other in memory - this is key for performance.

As for your second question: unfortunately, KeOps is not really meant to work with very high-dimensional vectors (say, with `D > 1,000`). We're actively working on supporting matrix-vector products with many columns for the right-hand side (see e.g. #30, #57), but the best solution will depend on your precise use-case. 
In practice, what are the typical values for `M`, `N` and `D` that you would like to use?

Best regards,
Jean

**Comment by arahiche** [comment]
Thank you @jeanfeydy for your answer. 
I thought that data representation in the .mat file is the problem, but the issue occurs only when I multiply the LazyTensor with the data. Fortunately, the .contiguous() method helped to reshape my matrices.

Typically, `M >10^6` but `N < 300, and D < 10`.

**Comment by jeanfeydy** [comment]
Hi @arahiche ,

I am not sure that I understand your problem very well: could you please provide an example of code that fails on your machine?
As far as I can tell, the code below should work fine, and be very efficient:

```python
import torch
from pykeops.torch import LazyTensor
use_cuda = torch.cuda.is_available()
dtype = torch.cuda.FloatTensor if use_cuda else torch.FloatTensor
D = 10
M = 1000000
N = 300

# Create some data:
x = torch.randn(M, D).type(dtype)  
y = torch.randn(N, D).type(dtype)
b = torch.randn(K_ij.shape[1], D).type(dtype)

# torch.Tensor -> LazyTensor conversion:
x_i = LazyTensor(x[:, None, :])  # (M, 1, D) LazyTensor
y_j = LazyTensor(y[None, :, :])  # (1, N, D) LazyTensor

# Operations on LazyTensors:
D_ij = ((x_i - y_j) ** 2).sum(-1)   # Symbolic (M, N) matrix
K_ij = (- D_ij).exp()  # Symbolic (M, N) kernel matrix

# K_ij is a LazyTensor, b is a torch.Tensor -> a_i is a torch.Tensor
a_i = K_ij @ b
```

KeOps LazyTensors stand for "symbolic" matrices that are generally too large to be represented as dense matrices. As of today, there is no method that turns a full `(M, N)` LazyTensor into a dense `(M, N)` torch.Tensor. However, all reductions of a LazyTensor return a dense torch.Tensor: this is what happens here with the matrix-matrix product `K_ij @ b`, which is implemented as a weighted sum over the second dimension of `K_ij`.
Does this answer you question?

Best regards,
Jean

**Comment by jeanfeydy** [comment]
I'm closing this issue for now, as it seems to have been resolved. Feel free to re-open if needed!

**Comment by yaadhavraajagility** [comment]
@jeanfeydy Is this possible without doing the reduction? Converting lazytensor to tensor?
