### ISSUE TITLE
Pytorch MNIST example

### ISSUE THREAD

**Issue by srikanthmalla** [getkeops/keops#96]
Hi, 
This package seems to be of real value, especially for deep learning community using pytorch. Do you have some example with MNIST training (https://github.com/traveller59/spconv/blob/master/example/mnist_sparse.py) to show how to use this not only for very low level operations but also for training some convolution or rnn networks (I think the operations can be from pytorch right, if we want to use with pykeops). The reason I was asking is I'm surprised that when I added a small module using pykeops into my pytorch code, the overall gpu memory decreased by almost half. I'm very curious to learn how to use pykeops with pytorch with some example of MNIST. Please let me know.

Best Regards,
Srikanth

**Comment by jeanfeydy** [comment]
Hi @srikanthmalla ,

Thanks for your interest in the library! 

KeOps is now mature for applications to kernel methods and 3D geometry: expanding our engine and documentation to reach the deep learning community has become our main priority. Over the summer, we have written a collection of new tutorials that will be pushed online with the v1.5 and a new paper in October: they cover integration with [**PyTorch_geometric**](https://pytorch-geometric.readthedocs.io/en/latest/), [UMAP](https://umap-learn.readthedocs.io/en/latest/) and [RapidsAI/**cuML**](https://rapids.ai/). We also explain how to quickly compute **geometric descriptors** (curvatures, NN-based, etc.) on 3D point clouds or work with **embeddings** in hyperbolic spaces. I hope that you'll find them useful!

Going forward, we also plan to document KeOps implementations for common attention layers and are 100% open to suggestions for new tutorials. For [SparseConvs](https://openaccess.thecvf.com/content_cvpr_2018/papers/Graham_3D_Semantic_Segmentation_CVPR_2018_paper.pdf), fortunately, we can probably ask Benjamin Graham (@btgraham) for some advice: he has been using KeOps for more than a year now (#19, #45) and is in a perfect position to tell us if it can (or cannot) bring something here :-)

Best regards,
Jean

P.S.: You've probably seen it already, but there is a tutorial in the documentation that explains how to perform [K-NN classification on the MNIST dataset](http://www.kernel-operations.io/keops/_auto_tutorials/knn/plot_knn_mnist.html). Thanks to our new optimizations for high-dimensional variables (d5eda0d0910326a83ff4178d001bbb11d1688f41), KeOps v1.4.1 now scales up to the full dataset in 0.5s: a x20 speed-up compared with KeOps v1.4.

**Comment by srikanthmalla** [comment]
Hi @jeanfeydy ,
Sorry for pointing example to sparse convolutions. It doesn't have to be with sparse conv.

How about an example like this:  http://www.kernel-operations.io/keops/_auto_tutorials/knn/plot_knn_mnist.html for a pytorch based MNIST classifier: https://github.com/pytorch/examples/blob/master/mnist/main.py

Do you have an example with MNIST classifier based on regular pytorch operations to show how to use pykeops with pytorch (for reducing memory usage with very big batches). Please let me know.

Best Regards,
Srikanth

PS: good to hear about the integrations with pygeometric :)

**Comment by jeanfeydy** [comment]
Hi @srikanthmalla ,

It depends on what you want to achieve: unlike general purpose acceleration frameworks such as [TVM](https://tvm.apache.org/docs/index.html) or [XLA](https://www.tensorflow.org/xla), KeOps only optimizes a specific set of operations. As detailed in [our frontpage](http://www.kernel-operations.io/keops/index.html), we provide support for a new type of semi-symbolic tensors that are well suited to "mathematical" computations on sampled data. **Can it be useful for your own projects?**
- If you are working with convolutions on full images (i.e. standard CNNs) as in the example above, then probably **no**: cuDNN, TVM or Halide are as optimized as it gets for the job.
- If you are working with distance or kernel matrices (e.g. for Gaussian processes, geometric deep learning, attention layers...), then probably **yes**. It is a type of computation that has been mostly neglected by the main frameworks, and KeOps fills this gap.
- In other settings... **It depends**. Of course, we'll be happy to discuss it with you.

In this context, sparse convolutions are an interesting middle case: they sit in between convolutions on full images (for which KeOps is useless) and convolutions on point clouds (for which KeOps is very good). The specific C++ implementations of [SparseConvNet](https://github.com/facebookresearch/SparseConvNet) and [spconv](https://github.com/traveller59/spconv) are probably very efficient today... But KeOps may bring a little bit more flexibility to their developers. I don't know - but @btgraham certainly does.

As a conclusion, let's keep in mind that **KeOps is a useful but fairly specialized tool**. It only does "one" thing (add support for symbolic matrices), but it does it well (with top performance and a user-friendly documentation).
I hope that this answers your question :-) 

Best regards,
Jean

**Comment by jeanfeydy** [comment]
I'm closing this issue as it seems to have been resolved. We've tried to make the point above clearer in our [NeurIPS 2020 paper](https://www.jeanfeydy.com/Papers/KeOps_NeurIPS_2020.pdf): I'll re-write the introduction of the documentation next week to reflect this better :-)
